### PR TITLE
Fixes #2306. Nullable bool Checked for Menu and CheckBox.

### LINKED ISSUE #2306: Nullable bool Checked for Menu and CheckBox.
**Is your feature request related to a problem? Please describe.**
It's a bit frustrated when we are forced to create a `enum` or a `RadioGroup` to only use 3 options when we can use a nullable bool property.

**Describe the solution you'd like**
The feature of having a `Checked` property with 3 states of a nullable bool value (`null`, `true` and `false`).

**Describe alternatives you've considered**
I considered a workaround by the creation of the properties `AllowsNullChecked` and `NullChecked`, but the simple `get/set` of the `Checked` property will imply a very complexity way to get or set whatever is null, true or false. So, the ensured way to do this is by changing the `Checked` property to a nullable bool (`public bool? Checked`).

**Additional context**
To go ahead with this feature will cause a breaking change on the API and I only go forward with this if the effort and consequences are worthwhile. @tig and @tznind I only starting this if you both agreement.

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2306 - This feature will allow using the three states of a `nullable bool` (`null`, `true` or `false`) on `Menu` and `CheckBox` views.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

checkbox-null-checked

menu-null-checked

### CODE REVIEW

**Review by tig — CHANGES_REQUESTED** [review]
This needs to target the v2 branch. We can't accept such a big breaking API change into v1.x.

**Comment by BDisp** [comment]
> This needs to target the v2 branch. We can't accept such a big breaking API change into v1.x.

Sorry @tig, I didn't realized that this PR should to be in the v2 branch, but is v2 up to date with the v1.x?

**Comment by BDisp** [comment]
@tig do I need to merge the develop branch into the v2 branch before I submit the PR?

**Comment by tig** [comment]
> > This needs to target the v2 branch. We can't accept such a big breaking API change into v1.x.
> 
> Sorry @tig, I didn't realized that this PR should to be in the v2 branch, but is v2 up to date with the v1.x?

We can't take big breaking API changes into develop (v1).

**Pull request closed without merging**
