### PR TITLE
Adds Draw benchmarking support

### PR DESCRIPTION
**Pull request by tig**
This PR backports some drawing benchmark stuff from 

- #3798 

to quantify how much improvement I'm making.

## Proposed Changes/Todos

- [x] Add support to `ConsoleDriver` for tests to see how often draw code is called.
- [x] Add an `All_Scenarios_Time` unit test that measures how each Scenario performs w.r.t draw calls.

The results are pretty horrific.

For example. 

```
Scenario UICatalog.Scenarios.AllViewsTester
  took 20827 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 5004 times.
    which updated the screen 5003 times.

Scenario UICatalog.Scenarios.Generic
  took 4659 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 5004 times.
    which updated the screen 5003 times.

Scenario UICatalog.Scenarios.Progress
  took 12300 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 5004 times.
    which updated the screen 5003 times.
```

In #3798:

```
Scenario UICatalog.Scenarios.AllViewsTester
  took 91 ms to run.
  called Driver.ClearContents 1 times.
  called Driver.Refresh 5003 times.
    which updated the screen 1 times.

Scenario UICatalog.Scenarios.Generic
  took 16 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 5003 times.
    which updated the screen 1 times.

Scenario UICatalog.Scenarios.Progress
  took 84 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 5003 times.
    which updated the screen 1 times.
```

### CODE REVIEW

**Comment by tig** [comment]
More...

Before:

```cs
Scenario UICatalog.Scenarios.Buttons
  took 2271 ms to run.
  called Driver.ClearContents 0 times.
  called Driver.Refresh 1004 times.
    which updated the screen 1003 times.
  called View.Draw 22044 times.
```

After:

```
Scenario UICatalog.Scenarios.Buttons
  took 82 ms to run.
  called Driver.ClearContents 1 times.
  called Driver.Refresh 1003 times.
    which updated the screen 1 times.
  called View.Draw 41 times.
```

**Comment by tig** [comment]
These new tests expose some really bad behavior in a bunch of Views and Scenarios...

Most of which are caused by the API being unclear, which I'm fixing in #3798

**Comment by tznind** [comment]
Nice! this will make a huge improvement in performance! Thats like 20x less!

❤️

**Comment by tig** [comment]
Closing as I don't plan on backporting any more. This did the job of showing a rough baseline of how bad tings were and how much #3798 helps.

**Pull request closed without merging**
