### PR TITLE
Fixes 2342. Border: can't change border color in window by Border.BorderBrush.

### LINKED ISSUE #2342: Border: can't change border color in window by Border.BorderBrush
**Describe the bug**
The color of the Border depends on the ColorScheme of Window, when you try to change the color of the Border through the BorderBrush property, nothing happens.

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2342 - Include a feature to set the margin frame and title colors base on the setting of the `Border.BorderBrush` and the `Border.Background` properties. Also added xml documents to the true color.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — APPROVED** [review]
Good job.

**Comment by BDisp** [comment]
@tig I know you refactored very well the `Border` class in v2, but I think we can leverage this PR in the v1 and only accept the v2 version on merge conflicts. After doing once the merge conflicts doesn't appear anymore for the older changes. What do you think?

**Review by tig — APPROVED** [review]

**Comment by tig** [comment]
@BDisp can you please figure out the unit test failures?

**Comment by BDisp** [comment]
> @BDisp can you please figure out the unit test failures?

@tig it was fixed. There was some merge that cause this not properly work but now is ok. Thanks.

**Pull request merged**
