### PR TITLE
Fixes #2883. ProgressBar: 'Frame.DrawFrame(Rect, bool)' is obsolete: 'This method is obsolete in v2. Use use LineCanvas or Frame

### LINKED ISSUE #2883: ProgressBar: 'Frame.DrawFrame(Rect, bool)' is obsolete: 'This method is obsolete in v2. Use use LineCanvas or Frame
image

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2883 - Using the v2 Frame to deal with border.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
@BDisp are you going to merge in my PR https://github.com/BDisp/Terminal.Gui/pull/168?

**Comment by BDisp** [comment]
> @BDisp are you going to merge in my PR [BDisp#168](https://github.com/BDisp/Terminal.Gui/pull/168)?

I can but the unit tests are failing and I don't know what you want I do.

**Comment by BDisp** [comment]
> > @BDisp are you going to merge in my PR [BDisp#168](https://github.com/BDisp/Terminal.Gui/pull/168)?
> 
> I can but the unit tests are failing and I don't know what you want I do.

Done. Good improvement. Thanks.

**Comment by tig** [comment]
Please revert your merge of `v2_drawframe-method_2983` into this. It is not needed to make ProgressBar work as far as I can see. I'd like to get this merged now as I left it after I fixed the unit tests.

**Comment by BDisp** [comment]
The failing error on the `TestTreeViewColor` unit test it's already boring.

**Comment by BDisp** [comment]
Done @tig.

**Review by tig — APPROVED** [review]

**Pull request merged**
