### PR TITLE
Fixes #3696 Remove custom navigation in FileDialog

### LINKED ISSUE #3696: `FileDialog` has a non-standard/non-intuitive keyboard nav model
```cs
        // BUGBUG: This TabOrder is counter-intuitive. The tab order for a dialog should match the
        // order the Views' are presented, left to right, top to bottom.
        // Determines tab order
        Add (_btnToggleSplitterCollapse);
        Add (_tbFind);
        Add (_spinnerView);
        Add (_btnOk);
        Add (_btnCancel);
        Add (_btnUp);
        Add (_btnBack);
        Add (_btnForward);
        Add (_tbPath);
        Add (_splitContainer);
```

### LINKED ISSUE #3701: `FileDialog` doesn't show button shadows correctly
image

This is caused by the fact `FileDialog` doesn't take full advantage of `Pos/Dim` for layout.

Generally, the fix is 

- use `Pos.AnchorEnd` for any buttons that are supposed to be at the bottom/right.
- dont position views with absolute values, such as the "up" dir button

### PR DESCRIPTION
**Pull request by tznind**
## Fixes

- Fixes #3696 
- Fixes #3701
- Partially Addresses #3631

## Proposed Changes

Changes ok/cancel to use `Dialog.AddButton` for placing.

- [x] Anchor buttons end
- [x] Fill only to buttons for main view
- [ ] Using Dialog.AddButton will make search collide under some situations.
- [x] Remove old keyboard nav
- [x] TableView cursor allow focus change i.e. first/last col etc
  - [x] Tests for TableView cursor focus change
- [ ] ~TreeView cursor allow focus change i.e. when cannot expand/already expanded~
  - [ ] ~Tests for TreeView cursor focus change~*

\* worry about these later, user can still just tab out of the tree.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
image
_FileDialog both with and without 'Shadow Buttons'_

Ok I think this is nearly as requested.

Issues remaining on layout are:
- The `Fill` issue on main panel being sensitive to the height of the buttons
- The Search and Expand buttons are in the `Dialog` area for buttons so depending on the button alignment in settings could collide
- TreeView cursor focus changing, I think I will de-scope that as it is not really related.

Open to suggestions on how to deal with this.  We can move search up 1 row but that is starting to eat more screen realestate 🤷

**Comment by tig** [comment]
Just change the alignment style of the buttons added by Dialog to End. 

Add your two views using pos.align with alignment set to Left. Pick a unique GroupId.

**Comment by tznind** [comment]
> Just change the alignment style of the buttons added by Dialog to End.

> Add your two views using pos.align with alignment set to Left. Pick a unique GroupId.

Great, this seems to work:
[a8748ee](https://github.com/gui-cs/Terminal.Gui/pull/3712/commits/a8748eeb2254976b2b2fef6a957e95b88a123b46)

**Comment by tig** [comment]
FWIW, I think this discussion is why I prefer 

```json
 "Dialog.DefaultButtonAlignment": "End",
```

See #3493

**Review by tig — APPROVED** [review]

**Pull request merged**
