### PR TITLE
Fixes  #2078 - Add params constructor to View

### LINKED ISSUE #2078: Enable collection initializer syntax for View
Would be nice to add support for the more structural/declarative style allowed by 
collection initializers when creating views, such as:

```csharp
	var view = new View {
		new View {
			new View()
		},
		new View()
	};
```

The only reason this currently doesn't work is that `View` does not implement `IEnumerable`:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1922	Cannot initialize type 'View' with a collection initializer because it does not implement 'System.Collections.IEnumerable'	UnitTests	...Terminal.Gui\UnitTests\ViewTests.cs	122	Active
```

The view could implement that interface explicitly like so:

```csharp
IEnumerator IEnumerable.GetEnumerator () => Subviews.GetEnumerator ();
```

And that alone would enable this usage, since the class already provides an `Add(View)` method, which is 
the other thing the compiler looks for in this initialization pattern.

### PR DESCRIPTION
**Pull request by tznind**
Fixes  #2078 - Add params constructor to View for easier collection style initiation

Allows for declarative style construction e.g.

```csharp
root = new View (
	l1 = new View (
		l1_1 = new View ()
	),
	l2 = new View (),
	new Button ()
);
```

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
@BDisp  / @kzu / @tig do you want a `params` constructor on other 'container' type views e.g. `FrameView`, `Window`?

**Comment by BDisp** [comment]
> @BDisp / @kzu / @tig do you want a `params` constructor on other 'container' type views e.g. `FrameView`, `Window`? I think it makes sense but just wanted to check in. I'll leave it as draft for now and can add the other constructors if that is the consensus.

For those you must have careful to add to the `ContentView` instead into the containers itself. But I prefer to wait for the @tig answer.

**Comment by tig** [comment]
Should the underlying issue #2078 (which has been closed) be re-opened/named a target the v2 project?

**Comment by tig** [comment]
Closing. #2078 i still opened and in the v2 backlog. The code here can be retargeted to v2 when appropriate (and may just be part of #2360).

**Pull request closed without merging**
