### PR TITLE
Fixes #2432 - Adds `Dim.Auto` automatically size views based on content

### LINKED ISSUE #2432: Finish `Dim.Auto` - `DimAutoStyle.Content` is half-baked
This feature has been partially implemented. `DimAutoStyle.Text` works great and fully replaced `View.AutoSize`. However, `DimAutoStyle.Computed` is still a WIP. We'll close this issue once it's fully implemented and tested.

## Background

See #2431 for some context.

Multiple times I've wanted to have a view dynamically be sized based on it's subviews. Also we have `AutoSize` which sorta does this for `Text`. 

I'd like to propose the following for v2:

- A new feature for ComputedLayout that adds `Dim.Auto ()`
- Replace `AutoSize` with something that builds on `Dim.Auto ()`

I think this should be possible, but haven't thought THAT much about it.

```cs
view.Height = Dim.Auto ();  // Height will be Margin.Height+Padding.Height+Border.Height+(height required for all Subviews to fit).
```

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- Fixes #2432 

## Adds `Dim.Auto` to Computed Layout to automatically size views based on content

- [x] Initial WIP and Scenario to demonstrate concept
- [x] Support auto-size based on subviews
- [x] Figure out how to make `CheckDimAuto` deal with PosCombine
- [x] Re-investigate the concept of `Dim.AutoSize (max: n)` and/or `Dim.AutoSize (max: dim)` 
  - Without this, AnchorEnd doesn't work, which is really sad. 
- [x] Merge the fix to 
  - [x] https://github.com/gui-cs/Terminal.Gui/issues/3192
- [x] Support auto-size based on `Text`
- [ ] Implemement `Dim.AutoSize (min: dim)`
- [ ] Dive deep into all other PosDim objects and get clarity on behavior relative to `Dim.Auto` - Write unit tests to validate
  - [x] `Dim.Absolute`
  - [ ] `Dim.Auto`
  - [ ] `Dim.Fill`
  - [ ] `Dim.Function`
  - [ ] `Dim.Width`/`Height`
  - [x] `Pos.Absolute`/`At`
  - [ ] `Pos.AnchorEnd`
  - [ ] `Pos.Function`
  - [ ] `Pos.Anchor`
  - [ ] `Pos.Percent`
  - [ ] `Pos.Center`
  - [ ] `Pos.X`/`Y` etc...
- [ ] Implemement `Dim.AutoSize (max: dim)`
- [ ] Use `Dialog` and `MessageBox` as test cases - This will require moving the dialog buttons to `Padding` as adornments.
- [ ] Remove `View.AutoSize` and update all code to use `Dim.AutoSize` instead
- [ ] Ensure vertical text works
- [ ] Unit tests
- [ ] API docs

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
WindowsTerminal_EoIU6qEj1L

**Comment by tig** [comment]
`Dim.AutoSize(margin)` doesn't make sense afterall. Even if someone wanted to specify a margin, it's better to use `View.Margin` or `View.Padding` to accomplish this.

**Comment by tig** [comment]
The current implementation in this PR is intentionally restrictive. If `View.ValidatePosDim = true` it will throw exceptions if `DimAuto` is used where a subview references the SuperView's dimensions. 

It works, but the usefulness is somewhat limited as-is. I really want to use this for `Dialog` and `MessageBox`, but one of two things has to happen to make that work:

- We finish Adornments such that the dialog/mb buttons are in Padding.
- We add (min/max) to `DimAuto` such that the subviews can use `AnchorEnd` etc... I believe this is possible, but until it's implemented I may be missing something.

To this end, I'm going to merge this PR asap, based on @BDisp  and @tznind's reviews. Then, at a later time we can tackle improving it.

**Comment by tig** [comment]
Another topic: 

- [ ] Support auto-size based on `Text`

Specifically, how to determine whether `DimAuto` uses `Subviews` or `Text` to do its thing?

Choices:

1) Be explicit: `Dim.Auto (text: true)` (or `Dim.Auto (DimAutoStyle.Text)`/`Dim.Auto (DimAutoStyle.SubViews)`)?
2) Be implicit: If `Subviews.Count > 0` use Subviews, else use `Text`?
3) Be implicit: If `Subviews.Text.Length > 0` use `Text`, else use `Subviews`?
4) Be implicit: A combination of 2 and 3?

Originally, I think I wanted to do 4.

But, in the spirit of future extensibility, and applying the "principle of least surprise" I now am leaning to 1.

If this is combined with min & max, the API would look like this:

```cs
/// <summary>
/// Creates a <see cref="Dim"/> object that automatically sizes the view to fit all of the view's SubViews.
/// </summary>
/// <example>
/// This initializes a <see cref="View"/> with two SubViews. The view will be automatically sized to fit the two SubViews.
/// <code>
/// var button = new Button () { Text = "Click Me!", X = 1, Y = 1, Width = 10, Height = 1 };
/// var textField = new TextField { Text = "Type here", X = 1, Y = 2, Width = 20, Height = 1 };
/// var view = new Window () { Title = "MyWindow", X = 0, Y = 0, Width = Dim.AutoSize (), Height = Dim.AutoSize () };
/// view.Add (button, textField);
/// </code>
/// </example>
/// <returns>The AutoSize <see cref="Dim"/> object.</returns>
/// <param name="style">Specifies how <see cref="DimAuto"/> will compute the dimension. The default is <see cref="DimAutoStyle.Text"/></param>
/// <param name="min">Specifies the minimum dimension that view will be automatically sized to. NOT CURRENTLY SUPPORTED.</param>
/// <param name="min">Specifies the maximum dimension that view will be automatically sized to. NOT CURRENTLY SUPPORTED.</param>
public static Dim Auto (DimAutoStyle style = DimAutoStyle.Text, Dim min = null, Dim max = null)
{
	return new DimAuto (style, min, max);
}

/// <summary>
/// Specifies how <see cref="DimAuto"/> will compute the dimension.
/// </summary>
public enum DimAutoStyle {
	/// <summary>
	/// The dimension will be computed from the view's <see cref="View.Text"/>.
	/// </summary>
	Text, 

	/// <summary>
	/// The dimension will be computed from the view's <see cref="View.Subviews"/>.
	/// </summary>
	Subviews,
}
```

Thoughts?

**Comment by BDisp** [comment]
I think the option 1 is the best.

**Comment by tig** [comment]
> I think the option 1 is the best.

Just implemented it too. It works great.

**Comment by tig** [comment]
This works now: 

```cs

	var textField = new TextField { Text = "Type here", X = 1, Y = 0, Width = 20, Height = 1 };

	var label = new Label {
		X = Pos.Left (textField),
		Y = Pos.Bottom (textField),
		AutoSize = true,
		ColorScheme = Colors.Error
	};

	textField.TextChanged += (s, e) => {
		label.Text = textField.Text;
	};

	var resetButton = new Button () {
		Text = "P_ut Button Back",
		X = Pos.Center (),
		Y = Pos.Bottom(label)
	};

	var movingButton = new Button () { Text = "Press to make button move down.", 
		X = 0, 
		Y = Pos.Bottom (resetButton), 
		Width = 10
	};
	movingButton.Clicked += (s, e) => {
		movingButton.Y = movingButton.Frame.Y + 1;
	};

	resetButton.Clicked += (s, e) => {
		movingButton.Y = Pos.Bottom (resetButton);
	};

	var view = new FrameView () {
		Title = "Type in the TextField to make View grow.",
		X = 3,
		Y = 3,
		Width = Dim.Auto (min: Dim.Percent(50)),
		Height = Dim.Auto (min: 10)
	};
	view.ValidatePosDim = true;
	view.Add (textField, label, resetButton, movingButton);

	Application.Top.Add (view);
```

Note, esp, how `Width` uses `Dim.Auto (min: Dim.Percent (50))` and `Width` uses `Dim.Auto (min: 10)`. Woot!

**Comment by BDisp** [comment]
> Note, esp, how `Width` uses `Dim.Auto (min: Dim.Percent (50))` and `Width` uses `Dim.Auto (min: 10)`. Woot!

`Height` uses `Dim.Auto (min: 10)`.

Good work. Congrats.

**Comment by tig** [comment]
There's a lot of complexity introduced by this concept regarding potential recursion of LayoutSubviews. 

One potential simplification might be  to make the layout engine non-reentrant. IOW, for any view hierarchy a 'InLayout' flag would cause 'LayoutSubviews' to return immediately. 

Not sure I like this idea but posting it to get it out of my head 😉.

**Comment by tznind** [comment]
I agree 1.  Always better to be explicit than magic.  I can imagine e.g. a
view that auto wraps not wanting its `Text` to be assumed to indicate width.

**Comment by BDisp** [comment]
The only thing I don't like, but not related to this PR, is the color of the `Window` title when it is focused. It should be a color with the same background but with another foreground color.

**Comment by tig** [comment]
> The only thing I don't like, but not related to this PR, is the color of the `Window` title when it is focused. It should be a color with the same background but with another foreground color.

Please avoid commenting on unrelated things in discussions. Instead create a new issue. It makes it hard to focus.

**Comment by BDisp** [comment]
Do you already having test `Dim.Auto` with the vertical text direction?

**Comment by tig** [comment]
> Do you already having test `Dim.Auto` with the vertical text direction?

I did, and it was working. But then I broke it. 

I'll ensure it works.

**Comment by dodexahedron** [comment]
> > Do you already having test `Dim.Auto` with the vertical text direction?
> 
> I did, and it was working. But then I broke it.
> 
> I'll ensure it works.

Don't you hate that?

On one part of the recent work I've been doing, I somehow broke like 1200 tests and for the life of me I couldn't figure out how, even rolling back commit by commit.

Then I just reset to a known working point and it STILL didn't work.

Closed and restarted visual studio and it all worked. Rolled forward all of the commits from when it was broken.... And it worked. To be sure, I rebooted, stashed the changes from the branch point, made a fresh clone, and popped the stash. Everything worked and no changes were missed in the commits.

Sometimes it's Visual Studio's fault. 😆

**Comment by tig** [comment]
> Sometimes it's Visual Studio's fault. 😆

And sometimes it's the fault of unit tests that depend on all kinds of other crap in obtuse ways.

**Comment by dodexahedron** [comment]
> > Sometimes it's Visual Studio's fault. 😆
> 
> And sometimes it's the fault of unit tests that depend on all kinds of other crap in obtuse ways.

Ha yep.

Why did we choose this profession, again? 😅

**Comment by dodexahedron** [comment]
Oh hey just a tip for future event code or other cancelable code, since that happened to be the first file that actually expanded initially in the diff view here...

CancellationTokens should be used for cancellation, instead of custom implementations such as booleans.

My event refactor branch will be taking care of that for anything that already exists (and is making an attempt to do it in a shared code path, too, for consistency and because DRY), so don't worry about it for this. Just had the thought and wanted to share the tip.

**Comment by tig** [comment]
My head hurts thinking through all the combinations of PosDim objects relative to Dim.Auto. I've done enough experimentation to be convinced we can make things like `Pos.AnchorEnd`, `Pos.Center`, and `Dim.Fill` work for subviews of a view with a `Dim.Auto` dim. There will be some limitations (e.g. the `Dim.Auto` must have a `min` specified).

However, I also think there's huge value in `Dim.Auto` only supporting `Pos.At`, `Pos.Absolute`, `Pos.AnchorEnd`, and `Dim.Absolute` and `Dim.Height/Width`.

So, my plan is to continue a bit more experimentation and then push hard to get this PR merged with a limited implementation. We can then expand functionality later.

**Comment by tig** [comment]
Closing this and replacing with 

- #3416

**Pull request closed without merging**
