### PR TITLE
Fixes #3574. Enabling trim mode breaks program at runtime (v2 only)

### LINKED ISSUE #3574: Enabling trim mode breaks program at runtime (v2 only)
**Describe the bug**
Enabling trim mode when publishing a project using Terminal.Gui will throw this error when run. Disabling trim mode or reverting to v1 resolves this issue:

```cs
Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream , JsonSerializerOptions )
   at Terminal.Gui.SettingsScope.Update(Stream, String)
   at Terminal.Gui.SettingsScope.UpdateFromResource(Assembly, String)
   at Terminal.Gui.ConfigurationManager.Reset()
   at Terminal.Gui.ConfigurationManager.get_Settings()
   at Terminal.Gui.ConfigurationManager.Load(Boolean )
   at Terminal.Gui.Application.InternalInit(ConsoleDriver , String , Boolean )
   at Terminal.Gui.Application.Init(ConsoleDriver , String )
   at Program.<Main>$(String[]) in C:\Users\Admin\Workshop\FFBatchConverter\FFBatchConverter\Source\Program.cs:line 4
```

**To Reproduce**
1. Create a sample project, Something like this will suffice:
```cs
Application.Init();

try
{
	Application.Run(new Toplevel());
}
finally
{
	Application.Shutdown();
}
```
2. Publish the project with trim enabled.

**Expected behavior**
The program should work even with trim enabled, as it did for v1.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version 23H2, OS build 22631.37374

**Additional context**
[This link](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/publishtrimmed) recommends setting this flag in the .csproj file:
```xml
  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
```
as a workaround. This does not work, as it will give this error message at runtime:

```cs
Terminal.Gui ConfigurationManager encountered the following errors while deserializing configuration files:
Error deserializing resource://[Terminal.Gui]/Terminal.Gui.Resources.config.json: Unknown property name "$schema".
```

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3574

## Proposed Changes/Todos

- [ ] Add SourceGenerationContext

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

README:

# Terminal.Gui C# SelfContained

This example shows how to use the `Terminal.Gui` library to create a simple self-contained single file GUI application in C#.

With `Debug` the `.csproj` is used and with `Release` the latest `nuget package` is used, either in `Solution Configurations` or in `Profile Publish`.

To publish the self-contained single file in `Debug` or `Release` mode, it is not necessary to select it in the `Solution Configurations`, just choose the `Debug` or `Release` configuration in the `Publish Profile`.

When executing the file directly from the self-contained single file and needing to debug it, it will be necessary to attach it to the debugger, just like any other standalone application. However, when trying to attach the file running on `Linux` or `macOS` to the debugger, it will issue the error "Failed to attach to process: Unknown Error: 0x80131c3c". This issue has already been reported on [Developer Community](https://developercommunity.visualstudio.com/t/Failed-to-attach-to-process:-Unknown-Err/10694351). Maybe it would be a good idea to vote in favor of this fix because I think `Visual Studio for macOS` is going to be discontinued and we need this fix to remotely attach a process running on `Linux` or `macOS` to `Windows 11`.

### CODE REVIEW

**Review by tig — APPROVED** [review]
I don't understand most of these changes, but I'm super excited you figured it out!

Nice work!!!

**Comment by tig** [comment]
I think @dodexahedron should review this before we merge.

**Comment by tig** [comment]
@BDisp would it be possible (needed?) to fold the work @tznind did on

- #2423 

into this PR?

**Comment by tig** [comment]
FYI - tests are failing because of work i'm doing on trying to fix #3052. JFYI

**Comment by BDisp** [comment]
@tig, can you test the `Analyzers` unit tests on Linux to see if they are failing assertions due to the newline format, please? Thanks.

**Comment by BDisp** [comment]
> @tig, can you test the `Analyzers` unit tests on Linux to see if they are failing assertions due to the newline format, please? Thanks.

But in the VS2022, please.

image

**Comment by tig** [comment]
> > @tig, can you test the `Analyzers` unit tests on Linux to see if they are failing assertions due to the newline format, please? Thanks.
> 
> But in the VS2022, please.
> 
> image

Yep. 

image

**Comment by BDisp** [comment]
So I was right about the failure of these tests. The test files are in CRLF format, which means that on Windows the tests do not fail. But on Linux it fails because it uses the /n format for newlines. Changing the format to LF tests pass on Linux. As the CI is now using linux-ubuntu, the tests must be failing but it does not detect the source of the failure well. I am increasingly convinced that Analyzers are not well prepared to overcome certain unpleasantness.

**Comment by tig** [comment]
> So I was right about the failure of these tests. The test files are in CRLF format, which means that on Windows the tests do not fail. But on Linux it fails because it uses the /n format for newlines. Changing the format to LF tests pass on Linux. As the CI is now using linux-ubuntu, the tests must be failing but it does not detect the source of the failure well. I am increasingly convinced that Analyzers are not well prepared to overcome certain unpleasantness.

Interestingly, the Analyzers unit tests are not failing here (lines 183-294):

https://github.com/gui-cs/Terminal.Gui/actions/runs/9830843782/job/27137474915

image

**Comment by BDisp** [comment]
I confirm that the jobs are not failing.
But why doesn't it pass in VS2022. It's not just problems with my configuration because it's happening to you too.

**Comment by tig** [comment]
> I confirm that the jobs are not failing. But why doesn't it pass in VS2022. It's not just problems with my configuration because it's happening to you too.

I dunno. something with WSL?

**Comment by BDisp** [comment]
> I dunno. something with WSL?

Maybe because even running the test directly in WSL also fails. Naturally there is some configuration needed in WSL to map /r/n to /n automatically. But I have no idea. We already know that WSL uses many Windows dependencies and naturally is not separating them properly, just as the dockerfile does because it is independent of the host OS.

image

**Comment by BDisp** [comment]
The reason unit tests from the Analyzers project are not failing to execute actions is because the repository files are automatically written with the LF format on new lines when it is pushed to the respective operating system.
In Visual Studio 2022 it is using WSL to run unit tests but using the Windows 11 directory (/mnt/{drive}/{repo}) whose newline format is CRLF. Ideally, Visual Studio 2022 would first push the code to WSL, thus transforming the format of new lines as LF, and then run the unit tests. I wonder if this is possible.

**Comment by Mersid** [comment]
This dude right here, absolute mad lad 😎

**Comment by BDisp** [comment]
@Mersid did you already test this PR? Say if it's working with you. Thanks.

**Comment by tig** [comment]
@dodexahedron - Can we please get your review of this?

**Comment by BDisp** [comment]
It's failing again because the JETBRAINS_ANNOTATIONS.

**Comment by BDisp** [comment]
I have to remove JETBRAINS_ANNOTATIONS from the `Terminal.Gui` project to avoid this error.

```ps
╰─ .\SelfContained.exe
Unhandled exception. System.IO.FileNotFoundException:
File name: 'JetBrains.Annotations, Version=4242.42.42.42, Culture=neutral, PublicKeyToken=1010a0d8d6380325'
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo, RuntimeType)
   at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Type, Boolean)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo, Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Attribute.GetCustomAttribute(MemberInfo, Type, Boolean)
   at System.Attribute.GetCustomAttribute(MemberInfo, Type)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute(MemberInfo, Type)
   at Terminal.Gui.ConfigurationManager.<>c.<Initialize>b__48_8(PropertyInfo prop) in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 526
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1, Func`2)
   at Terminal.Gui.ConfigurationManager.<>c.<Initialize>b__48_2(<>f__AnonymousType1`2 <>h__TransparentIdentifier0) in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 524
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Terminal.Gui.ConfigurationManager.Initialize() in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 533
   at Terminal.Gui.ConfigurationManager.Reset() in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 342
   at Terminal.Gui.ConfigurationManager.get_Settings() in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 163
   at Terminal.Gui.ConfigurationManager.Load(Boolean reset) in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Configuration\ConfigurationManager.cs:line 269
   at Terminal.Gui.Application.InternalInit(ConsoleDriver driver, String driverName, Boolean calledViaRunT) in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Application\Application.cs:line 248
   at Terminal.Gui.Application.Run[T](Func`2 errorHandler, ConsoleDriver driver) in E:\Repos\CSharp\gui-cs\Terminal.Gui\Terminal.Gui\Application\Application.cs:line 702
   at SelfContained.Program.Main(String[]) in E:\Repos\CSharp\gui-cs\Terminal.Gui\SelfContained\Program.cs:line 13
```

**Comment by dodexahedron** [comment]
> It's failing again because the JETBRAINS_ANNOTATIONS.

Yep. I mentioned that somewhere. All that constant does is exactly that - sets the condition that makes them transitive.

It's fine to remove it, especially since I would have ended up taking it out in #3558 anyway.

I thought I _did_ already take it out in one of the PRs that just merged though?

**Comment by BDisp** [comment]
> I thought I _did_ already take it out in one of the PRs that just merged though?

See this comment https://github.com/gui-cs/Terminal.Gui/pull/3600/files#r1675696417 please.

**Comment by BDisp** [comment]
I removed the `Terminal.Gui.Analyzers.Internal` project from the `Terminal.Gui` project, deleted the `Directory.Build.*` and added the `JetBrains.Annotations PackageReference` to the `UICatalog` and `UnitTests` projects. Here the commit https://github.com/gui-cs/Terminal.Gui/pull/3582/commits/abdde3ab6c59b9ed66a5d21530d1bcdd1353f64d.

**Comment by tig** [comment]
@BDisp Ready for me to merge this now?

**Comment by BDisp** [comment]
> @BDisp Ready for me to merge this now?

Yes.

**Comment by BDisp** [comment]
I could also suggest publishing an update in the nuget and then testing in the Release version with the new version, if possible. Thanks.

**Comment by dodexahedron** [comment]
> I removed the `Terminal.Gui.Analyzers.Internal` project from the `Terminal.Gui` project, deleted the `Directory.Build.*` and added the `JetBrains.Annotations PackageReference` to the `UICatalog` and `UnitTests` projects. Here the commit [abdde3a](https://github.com/gui-cs/Terminal.Gui/commit/abdde3ab6c59b9ed66a5d21530d1bcdd1353f64d).

A rebase on v2_develop after the merges would have taken care of that too.

**Comment by dodexahedron** [comment]
> I could also suggest publishing an update in the nuget and then testing in the Release version with the new version, if possible. Thanks.

@tig @bdisp @tznind 

For anyone wanting to test nuget packaging:

You can dotnet pack locally and just add a local nuget source so you can install the package via standard nuget workflows. Then, multiple projects can make use of it and it doesn't disappear on you. It's the way you test before deploying/publishing to nuget.org or another public repository.

To set up a local feed, just make two directories in a common path outside of any git repos (this only needs to be done once):
 
 * One for the output of `dotnet pack -o path/to/pack/output/directory` for any projects you build packages from.
 * One to be your local nuget repository feed (path/to/feed/directory).

To update your feed with your latest builds, run `nuget init path/to/pack/output/directory path/to/feed/directory`

To use the feed, just add that feed as a nuget source.

Note that our current nuget.config in the repository root will nuke your custom feed because of the clear element, so either remove that line or just add your feed in that file instead.

Sourcelink warnings or errors are resolved by adding a mapping for your feed.

I prefer to do it by just explicitly specifying a custom nuget.config file on the command line when testing the `nuget restore`/`dotnet restore`, so it only uses the local feed when I explicitly want it to and doesn't affect anything otherwise.

**Comment by dodexahedron** [comment]
A similar but simpler procedure can also be used to set up a local powershell gallery, for ease of installing/importing powershell modules without needing to navigate to the containing directory.

I have several such custom local psrepositories on all of my dev machines, as well as PSDrives for solution directories as PSDrives that are created when powershell launches, as part of my powershell profile.

**Comment by dodexahedron** [comment]
Hm... You know what...

Yeah, a LOT of stuff reverted after that, including stuff from other PRs.

There's a strong possibility of regressions beyond just the project references and that PR.

**Comment by dodexahedron** [comment]
About the root cause of that sort of thing:

Almost definitely happened during merge conflict resolution on a branch.

Be extra careful to analyze conflicts that are not just edits on each side, and are instead add/edit/remove on one side and a different operation on the other side.

Those merge errors are a lot easier to catch with proper rebasing/merging procedures.

**Comment by dodexahedron** [comment]
Oh yeah.

There's also https://int.nugettest.org/ for when you want to test it over the internet but not live on nuget.org.

**Comment by BDisp** [comment]
To testing nuget packages locally I use the following:

In the `nuget.config`:

`<add key="Terminal.Gui" value="{Drive}:\{Path}\Terminal.Gui\Terminal.Gui\bin\Release" />`

I created a `Package.ps1` file with:
```ps
$Version = "2.0.0"

# Delete previous package
rm -r $env:USERPROFILE\.nuget\packages\terminal.gui\$Version

# Install dependencies
dotnet restore

# Build Release
dotnet build --no-restore -c Release

# Pack
dotnet pack -c Release --include-symbols -p:Version=$Version

```

**Comment by dodexahedron** [comment]
Yep. That's the way. 🙂 At least to pack it. Still need to test the install/restore and build in both visual studio and dotnet cli afterward.

Side note:

Another option for anyone who doesn't want to bother with the nuget.config is you can call `dotnet restore --source path/to/directory/containing/the/package --force --force-evaluate` to restore from just that path, ignoring other sources. You can specify --source multiple times in the command, if you want to also have it consider other sources, too.

**Pull request merged**
