### PR TITLE
Fixes #3784. SelfContained and NativeAot projects should use the local package in the release mode.

### LINKED ISSUE #3784: SelfContained and NativeAot projects should use the local package in the release mode.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3784

## Proposed Changes/Todos

- [x] Provide local packages in release mode

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
@tig I already fixed this issue locally but not yet in the github actions. Can you help me on this please. I don't have experience on this.

**Comment by tznind** [comment]
Looks like it is currently failing on the windows style local packages?

> /home/runner/work/Terminal.Gui/Terminal.Gui/NativeAot/NativeAot.csproj : error NU1301: The local source '/home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/bin/Release' doesn't exist. [/home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.sln]

If this source should only be used locally when checked out? you can remove it in the CI with:

```
dotnet nuget remove source LocalPackages
```

**Comment by BDisp** [comment]
> What is the goal of this PR?
> 
> To build a nuget package of Terminal.Gui in Release configuration to a directory and have the other two projects reference it?

Yes, only for the two projects that use the nuget package. It's to prevent, when the latest nuget version has significant changes, like now, to avoid the fail of these two projects at compile time, locally and in the github CI.

**Comment by tznind** [comment]
Was this already merged in another PR? it looks quite broken...

I would:

Firstly move the `nuget.config` file to the subdirectories where its needed i.e. into the NativeAot and SelfContained directories (cut paste).  This will prevent everyone trying to use this source even when it doesnt exist yet.

You may need to change the paths e.g. to `../local_packages` 

Pack only Terminal.Gui:

```
cd Terminal.Gui && dotnet pack --configuration Release --output ./local_packages
```

Remove the reference in the csproj files and add a new one to the Terminal.Gui in the local packages dir 


```
cd SelfContained
dotnet remove package Terminal.Gui
dotnet add package Terminal.Gui --source LocalPackages
```

**Comment by tznind** [comment]
Incidentally when I try to pack Terminal.Gui in WSL I get:

```
dotnet pack --configuration Release --output ./local_packages
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/lib/dotnet/sdk/8.0.110/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file '/mnt/d/Repos/temp/gui.cs/Terminal.Gui/bin/Release/net8.0/fr-FR/Terminal.Gui.resources.dll' to be packed was not found on disk. [/mnt/d/Repos/temp/gui.cs/Terminal.Gui/Terminal.Gui.csproj]
```

**Comment by tznind** [comment]
The closest one to the code is used I think so if you move it to subdirectory it will be used

**Comment by BDisp** [comment]
> The closest one to the code is used I think so if you move it to subdirectory it will be used. Basically when you are `cd` into the directory and building it will use the one that is in the current directory otherwise it will look at parent directory.

Yes I know, but normally `dotnet build --configuration Release` is done in the solution location and is the nuget.confile in that folder that will be used, I think. Feel free to submit your own PR that could fix this locally and in the CI and I will close, mine. In mean wile I'll continue to discover any solution that can solve this. Thanks.

Note: I did a cherry-pick of this commit https://github.com/gui-cs/Terminal.Gui/pull/3785/commits/d77b899db92b0fdd746f11f68144de8ad0e0fce5 in this PR.

**Comment by tznind** [comment]
Here is a first pass

https://github.com/BDisp/Terminal.Gui/pull/200/files

**Comment by BDisp** [comment]
> Here is a first pass
> 
> https://github.com/BDisp/Terminal.Gui/pull/200/files

I can't merge it. When you have sure it work mark as ready for review, please. Thanks.

**Comment by BDisp** [comment]
I think I found a simpler solution for this. We cannot avoid the `dotnet build` running immediately the package restore, avoiding the pre-build take the necessary tasks for build and pack the `Terminal.Gui` in release and thus, `NativeAot` and `SelfContained` projects restoring the packages with available package sources. The solution I found was creating a .ps1 file for Windows and .sh file for Linux and Mac. When we need to build a release version then we use that files for build and pack and then restore and build `NativeAot` and `SelfContained` projects.

**Review by tig — APPROVED** [review]

**Comment by tig** [comment]
Is this ready or not?

**Comment by BDisp** [comment]
> Is this ready or not?

Yes it's.

**Comment by BDisp** [comment]
If you don't mind it will useful to merge this to avoid all the CI errors. Thanks.

**Comment by tig** [comment]
@BDisp Release build is still failing

image

**Comment by BDisp** [comment]
> @BDisp Release build is still failing

Solution here https://github.com/gui-cs/Terminal.Gui/issues/3790#issuecomment-2407749053.

**Pull request merged**
