### PR TITLE
Fixes #2775. Something in 1.13 broke centering child windows.

### LINKED ISSUE #2775: Something in 1.13 broke centering child windows
**Describe the bug**
On 1.12.1, a child window added to another window at run-time, with X and Y set to Dim.Center() is displayed in the center of the parent Window that it is added to.

In 1.13.x, the child window is placed at 0,0 when shown. This occurs on Ubuntu 23.04 and on Windows 11 in PowerShell.
If the terminal is resized down and then to a size larger than the child window, it then centers itself.

I set a breakpoint to see what was going on.

In 1.13.x, the superview of the child has 0 width and height, even though the parent Window itself has the expected dimensions.
In 1.12.x, the superview of the child has the expected dimensions of the parent window.

Note that both of these Windows were created using the TerminalGuiDesigner tool.

The code used to add the child to the parent is just three lines (edited for verbosity):

```c#
//Elsewhere in the parent window class:
ChildWindowClass _childWindowAsAFieldBelongingToParentWindow = null;

//Function called by any means to create and show the child for the first time:
public void FunctionThatAddsTheChildWindow()
{
        _childWindowAsAFieldBelongingToParentWindow ??= new( );
        Add( _childWindowAsAFieldBelongingToParentWindow );
        ShowChild( _childWindowAsAFieldBelongingToParentWindow );
}
```

**To Reproduce**

Using 1.13.X (seems broken for any version of 1.13):
1. Create a Window with width and height = Dim.Fill(0)
2. Create a Window with explicit dimensions (any will do, so long as they're smaller than the terminal), and with X and Y = Dim.Center().
3. Add that second Window to the first Window, and show it.
4. The child window will be at 0,0,

**Expected behavior**
The child window should be shown positioned at the center of the parent window it was added to, as in 1.12.

**Desktop (please complete the following information):**
 - OS: Windows 11 and Ubuntu 23.04
 - Terminal: Happens on any terminal emulator or shell I've tried, including just at a bash prompt, tmux, screen, and zsh.

Started happening after updating to the 1.13 release series.
No code changes were made.

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2775 - `Application.Begin` always call `LayoutSubviews` but when a view is added after the app is running all the views that overridden `Redraw`'s method must call it explicitly.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
https://github.com/gui-cs/Terminal.Gui/assets/13117724/3dd68285-8a85-49d8-b1e6-d98415e4a819

**Review by tig — APPROVED** [review]

**Review by tig — APPROVED** [review]

**Comment by BDisp** [comment]
I resolved the conflicts but I can't run it neither the develop branch. See https://github.com/gui-cs/Terminal.Gui/issues/2815#issuecomment-1699333755.

**Comment by BDisp** [comment]
> I resolved the conflicts but I can't run it neither the develop branch. See [#2815 (comment)](https://github.com/gui-cs/Terminal.Gui/issues/2815#issuecomment-1699333755).

Done. Now it's working.

**Review by tig — APPROVED** [review]

**Comment by dodexahedron** [comment]
Nice change set. Fixed a couple of things I thought were my fault in another application.

And of course I'm certainly happy about the fix for #2775 being part of this PR 😅 

Thanks for your efforts. 👍

**Pull request merged**
