### PR TITLE
Fixes #3757. ShadowView throws System.IndexOutOfRangeException if left is less than zero.

### LINKED ISSUE #3757: ShadowView throws System.IndexOutOfRangeException if left is less than zero.
Try move a Dialog with shadow enabled to the left and you see this error. i.e. the about UICatalog dialog.

image

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3757

## Proposed Changes/Todos

- [x] Prevents X being less than zero.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — COMMENTED** [review]
I've fixed this and a few more in another PR.

**Comment by BDisp** [comment]
> I've fixed this and a few more in another PR.

@tig this is still happening in the v2_develop branch. If you are going to releasing a new version, please don't forget to fix this. Thanks.

**Comment by tig** [comment]
> > I've fixed this and a few more in another PR.
> 
> @tig this is still happening in the v2_develop branch. If you are going to releasing a new version, please don't forget to fix this. Thanks.

It's fixed in #3691

**Comment by BDisp** [comment]
> It's fixed in #3691

With the PR #3749. Right?

**Comment by BDisp** [comment]
> With the PR #3749. Right?

I already confirmed that is really fixed.

**Pull request closed without merging**
