### PR TITLE
Improves `KeyBindings`

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- This PR was extracted from #3531 - I made a bunch of improvements to KeyBindings there and don't want to wait to get them merged.

## Does not fix (for another PR)

- #3120

## Proposed Changes/Todos

- [x] Break `Application.cs` up
- [x] `KeyBinding` -> `record struct`
- [x] Move `KeyBindingScope.Application` logic into `Application`
- [x] More/better unit tests
- [x] Add context to Command invocations so handlers can see what key was pressed and scope if needed.
  - [x] Add `CommandContext` with `Command`, `Key`, and `KeyBinding` and extend (optionally) the Command fn to take a context param.
  - [x] Add `KeyBinding.Context`  to hold arbitrary context. 
- [x] Update `Menu` and `MenuBar` to use `KeyBinding.Context` instead of overriding `OnInvokingKeyBindings` 
- [x] Add `KeyBindings` scenario 
- [x] Finish `KeyBindings` Scenario
- [x] Git rid of `OnInvokingKeyBindings` overrloads in `RadioGroup` and `StausBar` now that we have context.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
Changing back to Draft as I want to fix a few more things and also fix

- #3120

**Review by BDisp — APPROVED** [review]
Very well organized and well planned.

**Comment by tig** [comment]
> Very well organized and well planned.

Thanks.

Did you look at what I did with the Find/Replace window in Editor?

**Comment by BDisp** [comment]
> Thanks.
> 
> Did you look at what I did with the Find/Replace window in Editor?

I really like the look of the border.
I just don't know why now the buttons don't have the same width as the larger size and with the text centered, as I initially designed. I liked the buttons better when they were all the same width instead of the current right alignment.

**Comment by tig** [comment]
> > Thanks.
> > Did you look at what I did with the Find/Replace window in Editor?
> 
> I really like the look of the border. I just don't know why now the buttons don't have the same width as the larger size and with the text centered, as I initially designed. I liked the buttons better when they were all the same width instead of the current right alignment.

Better?

UlnKWev 1

Got rid of the cancel button as we'll soon have the ability to have a close button in the title.

This uses Pos.Align to align the buttons.

**Comment by BDisp** [comment]
Yes it looks better, but do you know why now we can't set a wider width for a button without using `Dim.Auto`?

**Comment by tig** [comment]
> Yes it looks better, but do you know why now we can't set a wider width for a button without using `Dim.Auto`?

I'm not sure what you mean.

Are you saying `btn.Width = 30` gets ignored?

**Comment by BDisp** [comment]
Yes.

**Comment by tig** [comment]
> Yes.

image

**Comment by tig** [comment]
> > Yes.
> 
> image

Oh, do you mean you want the brackets to be pushed out to the sides?

Is that how it used to work?

**Comment by tig** [comment]
> > > Yes.
> > 
> > 
> > image
> 
> Oh, do you mean you want the brackets to be pushed out to the sides?
> 
> Is that how it used to work?

V1 worked as v2 does now:

mTQZy98 1

**Comment by BDisp** [comment]
That's exactly what I was referring to, sorry for not making me understand right away. It's not enough to just increase the width of the button, it's also necessary to push the brackets to both sides to get a more realistic view of its size, as just the color isn't enough.
Now in both v1 and v2 it may be working like this but I remember the brackets adjusting to the width of the buttons, in the past.

**Comment by tig** [comment]
> That's exactly what I was referring to, sorry for not making me understand right away. It's not enough to just increase the width of the button, it's also necessary to push the brackets to both sides to get a more realistic view of its size, as just the color isn't enough. Now in both v1 and v2 it may be working like this but I remember the brackets adjusting to the width of the buttons, in the past.

I don't remember it ever working that way, but my memory sucks so... 

Anyway, this code (similar to what's in v2) is the crux:

```cs
/// <inheritdoc/>
protected override void UpdateTextFormatterText ()
{
	if (IsDefault)
		TextFormatter.Text = ustring.Make (_leftBracket) + ustring.Make (_leftDefault) + " " + Text + " " + ustring.Make (_rightDefault) + ustring.Make (_rightBracket);
	else
		TextFormatter.Text = ustring.Make (_leftBracket) + " " + Text + " " + ustring.Make (_rightBracket);
}
```

I can see why someone would want what you are describing. Seems pretty low priority though. A workaround is to just make `Text` bigger using spaces.

**Comment by BDisp** [comment]
@tig I think `Alignment.Fill` does what it's expected more or less.

image

**Pull request merged**
