### PR TITLE
V1-Fixes #3738. CursesDriver stops responding.

### LINKED ISSUE #3738: Application stops responding
**Describe the bug**
In less than minute the application is not responding anymore. No exception is thrown.

**To Reproduce**
```using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Terminal.Gui;

namespace Playground
{
    public class Program
    {
        // Same issue with class List
        private static ObservableCollection<string> List = new();
        private static ListView ListView = new();
        private static Timer? _timer;

        public static void Main(string[] args)
        {
            List.CollectionChanged += (obj, args) =>
            {
                Application.MainLoop.Invoke(() =>
                {
                    if (List.Count == 100) List.RemoveAt(0);
                    ListView.MoveDown();
                    ListView.SetNeedsDisplay();
                });
            };

            ListView = new ListView()
            {
                Width = 16,
                Height = 12,

            };
            ListView.SetSource(List);

            ListView.Enter += (args) =>
            {
                // We can use Application.MainLoop.AddTimeout(timespan, callback) but it will behave the same.
                _timer = new Timer(Refresh, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(2));
            };

            Application.Init();
            Application.Top.Add(ListView);
            Application.Run();
        }

        private static void Refresh(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                List.Add(new Random().Next(100000, 999999).ToString());
            });

        }

    }
}

```

**Desktop:**
`Tested with Apple Silicon & Linux x64 and arm64`

**Additional context**
Tested with Windows ARM and the application is working correctly in 5min timeframe.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3738

## Proposed Changes/Todos

- [x] Fix bug in the read method that was reading the second index instead the first in mainloop callback.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — APPROVED** [review]

**Comment by tomba** [comment]
@tig Could a new v1 version be tagged and a nuget package made? Without this fix, a thread will run in busy loop as the pipe always has data to read.

**Comment by tig** [comment]
Yeah. I'll do this asap!

**Comment by tig** [comment]
v1.18.0 has been published!

https://www.nuget.org/packages/Terminal.Gui/

**Comment by tomba** [comment]
> v1.18.0 has been published!

Thanks, works like a charm!

**Pull request merged**
