### PR TITLE
Fixes #2789. StatusItem should have a disabled attribute if it can't execute.

### LINKED ISSUE #2789: StatusItem should have a disabled attribute if it can't execute.
This will help a user see if a status item can be executed or not.

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2789 - Adding `CanExecute` property allow leveraging  the power of conditional executions.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
Why is this targetting v1? We agreed we will not add new capabilities to v1, but only v2.

**Comment by BDisp** [comment]
> Why is this targetting v1? We agreed we will not add new capabilities to v1, but only v2.

@tig I consider this a compatible change for v1 with no breaking change and I'll also submit a PR targeting to the v2 as well. The first release for v2 will take still a long time and we need to keep v1 pleasant as possible. I really hope you understand my observation.

**Comment by BDisp** [comment]
> But we agreed we were not adding anything new to v1. Every bit of focus we put into v1 delays v2.
> 
> I think we're pretty close to getting v2 done. We just need to focus on it!

@tig we agree not adding new features but not nothing about improving the existing one. I'm focused on v2 but actually I felling some like blocked without know where to go for now. What I did on `StatusItem` was something that was omitted before. I think constantly breaking only some improvements that do not compromise the existing code at all, it is not healthy to continue to keep any enthusiasm to really collaborate. Sorry but that's what I really feel. Please tell me what the code contained in this PR, breaks any compatibility with the code that the user currently uses. If you show me that this is the case I immediately close this PR. Also, as we know better v1, these improvements help us also implement v2 with more refined improvements. I think we should keep users as satisfied as well as possible with v1 to keep them and are more anxious for the official release of v2.

**Comment by tig** [comment]
> I'm focused on v2 but actually I felling some like blocked without know where to go for now.

The Project has tons of things that need working on. https://github.com/orgs/gui-cs/projects/1/views/1

image

> I think we should keep users as satisfied as well as possible with v1 to keep them and are more anxious for the official release of v2.

I do not see where a real customer has asked for this functionality. Did I miss that?

**Review by tig — APPROVED** [review]
Please also submit a v2 PR for this. Thanks.

**Comment by BDisp** [comment]
> Please also submit a v2 PR for this. Thanks.

Rest assured. All the PR's you ask or asked to submit to v2 I will do it. Don't forget to merge this one, please :-)

**Pull request merged**
