### PR TITLE
Fixes #3816. Visual Studio 17.12 isn't compatible with SDK version 8.0.0

### LINKED ISSUE #3816: Visual Studio 17.12 isn't compatible with SDK version 8.0.0
It's needed to change the version in the `global.json` file to `"version":"9.0.0"` for both, v1 and v2.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3816

## Proposed Changes/Todos

- [v] Upgrade all files to the net9.0 version

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
image


Builds fine for me, maybe it was the specific version of dotnet 8 you had installed?

**Comment by BDisp** [comment]
What version of net80 you are using?

**Comment by BDisp** [comment]
Do you also have the net90 version installed? I didn't install it but the VS2022 did when updated. Doesn't this happened with you?

**Comment by BDisp** [comment]
Working now, thanks.

**Pull request closed without merging**
