### PR TITLE
Fixes #3178. v1 - Library has no strong-name.

### LINKED ISSUE #3178: Library has no strong name
I need to use this library in my project which must have all the assemblies strong-named.

Could you consider signing the assembly with a public sign, please?

### PR DESCRIPTION
**Pull request by ilCosmico**
Add strong-name signing.

## Fixes

- Fixes #3178

## Proposed Changes/Todos

- [x] Add snk file
- [x] Add strong naming sign

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [ ] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by ilCosmico** [comment]
I suppose that [NStack library](https://github.com/gui-cs/NStack/) should be strong-named too.

image

**Comment by ilCosmico** [comment]
All tests passed!

image

BTW I'm not so expert on this library, so I don't now how to "to assure all features are working".

**Comment by ilCosmico** [comment]
Created PR [#91](https://github.com/gui-cs/NStack/pull/91) for NStack.

I tried to build again this version of Terminal.Gui with it and strong-name warning has now disappeared.

image

**Comment by tig** [comment]
> BTW I'm not so expert on this library, so I don't know how _"to assure all features are working"_.

Yeah, that's worded a bit unfairly.

Please, at least, do this:

- [ ] Run the All Views Tester Scenario and select each view. Ensure nothing really odd happens.
- [ ] Try a bunch of Scenarios. Some are more complex and tend to push the envelope and are good at sniffing out issues:
  - [ ] CharMap
  - [ ] Scrolling
  - [ ] Text Formatting
  - [ ] Editor
  - [ ] Dialogs
  - [ ] Wizards
- [ ] Do the above under WSL
- [ ] Do the above with `-usc` on both Windows and WSL

**Comment by ilCosmico** [comment]
@tig, @BDisp, I just added a strong-name option without changing the code. I don't think it compromises the library's running, do you?

**Comment by BDisp** [comment]
I don't think so and the tests pass. But you have to wait for @tig's decision.

**Comment by tig** [comment]
Do I need to do anything other than merge this for it to work for publishing to Nuget?

I was expecting to have to generate a private key that we'd need to store in a github secret or something.

**Comment by ilCosmico** [comment]
It is not necessary to generate a password for the .snk file for strong name purposes, so you just need to merge it. Thank you, @tig.

**Review by tig — APPROVED** [review]

**Comment by tig** [comment]
Ok, NStack v1.1.1 is published with an SN. 

Now for Terminal.Gui...

**Comment by tig** [comment]
v1.15.1 is published.

Please verify that I didn't screw something up ;-)

**Pull request merged**
