### PR TITLE
Fixes #2539. Menu should use Frame instead of DrawFrame.

### LINKED ISSUE #2539: Menu should use Frame instead of DrawFrame

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2539 - Include a terse summary of the change or which issue is fixed.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — APPROVED** [review]
Hero!

At some point, it seems Menu would be better off just being a view where each menu item is just a `View` (a `Label`?). Each 'frame' (e.g. separators) the menu would then be those View's `Border`.

**Comment by BDisp** [comment]
Well I was very lazy and I only used the view frame and the internal menu separator by changing the coordinates, but it could also be in the way you point to.

**Comment by tig** [comment]
Well your lazyness just caused me a bunch of work because I assumed you had done it carefully. 😠 💘

I'm merging #2483 now, but you'll see me merging in this PR into it broke some Menu tests that I had to disable because I ran out of time.. I'd love it if you'd look at them.

`Menu.cs` will be about 30% shorter if it can be made to fully leverage `LineCanvas`.

Thanks.

**Comment by BDisp** [comment]
@tig in the case of the `Menu` there is no need to use `LineCanvas`, with `Frame` it works well. Beside that I must understand better how it works. I'll see the unit tests.

**Comment by BDisp** [comment]
@tig you are mixing `Frame` with `LineCanvas`. Also the `OnRenderLineCanvas` must be call at the beginning of the Draw. What is bad in your design is that you are drawing the `Border` after the subviews content are drawn. To draw normal frame the `Frame` is ore than sufficient. If you want join borders then we must use the `LineCanvas`, but using both in the same view is very stranger.

**Comment by BDisp** [comment]
@tig I swear I already had the menu to work before but something broke it. Is it not possible to draw a simple edge around the view frame? Run `UICatalog` and you'll see the menu is working as expected.

**Comment by tig** [comment]
> @tig you are mixing `Frame` with `LineCanvas`. Also the `OnRenderLineCanvas` must be call at the beginning of the Draw. What is bad in your design is that you are drawing the `Border` after the subviews content are drawn. To draw normal frame the `Frame` is ore than sufficient. If you want join borders then we must use the `LineCanvas`, but using both in the same view is very stranger.

My design is not fully implemented yet. If you read the spec you'll see that.

When this is all complete the `Frame`s will be drawn INDEPENDENTLY and BEFORE the View's content is drawn.

See https://github.com/gui-cs/Terminal.Gui/issues/2482

**Comment by BDisp** [comment]
> Hero!
> 
> At some point, it seems Menu would be better off just being a view where each menu item is just a `View` (a `Label`?). Each 'frame' (e.g. separators) the menu would then be those View's `Border`.

I understand what you mean but it will imply a full refactor on the `Menu` which I don't know it it worth. I'll add the enable/disable border feature in the menus.

**Comment by BDisp** [comment]
For those much more brave than me here is a suggestion for two items without separator (remember that each member is a `View`):


```
┌───────┐
│ One   │
└───────┘
┌───────┐
│ Two   │
└───────┘

```
Since there is no separator the bottom thickness of the `One` item must be 0 and the top thickness of the `Two` item must also be 0. This will result the follow output:

```
┌───────┐
│ One   │
│ Two   │
└───────┘

```

More harder is when a separator is needed. In this case the bottom thickness of the `One` item must be 1 (default) and the top thickness of the `Two` item must be 0. This will result the follow output:

```
┌───────┐
│ One   │
└───────┘
│ Two   │
└───────┘

```

But the job isn't finished yet. It's needed to join the left with a `├` and on the right with a `┤` and the final result will be the follow output:

```
┌───────┐
│ One   │
├───────┤
│ Two   │
└───────┘

```
I don't want to give any lesson to anyone, but I only alert for the complexity, not for the steps above, but to the views that must be added to the superview and beside dealing with all menu/sub-menus opened, we needed to handle more much more views than currently has.

**Comment by tig** [comment]
The whole point of my latest big pr was to make two views that touch blend borders automatically!

Just set UseSuperviewLineCanvas = true

**Pull request merged**
