### PR TITLE
Fixes #3597: Convert package reference versions to ranges

### PR DESCRIPTION
**Pull request by dodexahedron**
Here's what the changes necessary to switch to ranges look like, as mentioned in #3597 

## Fixes

- Fixes suggestions made in #3597

## Proposed Changes/Todos

- [x] Switch to version ranges for PackageReference elements 

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [ ] My changes generate no new warnings
       - Warnings generated are informational from NuGet, to let you know what the result of the package resolver was. 
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by BDisp — APPROVED** [review]
LGTM.

**Comment by dodexahedron** [comment]
Just to note:

I mostly just used existing versions as inclusive lower bounds, with the next major version as exclusive upper bounds.

A few have unbounded maximum versions, but that's mainly just things that are design-time only like the JetBrains packages that change frequently and are highly unlikely to break anything on a "major" version bump, since they just use a non-semver year.x.y versioning scheme.

And of course if they ever did break a build, all you gotta do is put an appropriate upper bound or update code to work with the new version and it's all done.

**Comment by dodexahedron** [comment]
You may have also noticed how the `<PackageReference Update=...` elements got removed from csproj files.

That's a nice little side-benefit this gives, for packages that are in the Directoy.Build.[props|targets] files, which happen when visual studio is used to update a package version for one of those packages, since Visual Studio doesn't _actually_ support the central management completely.

**Review by tig — APPROVED** [review]
This makes me have warm feels. Thanks.

**Pull request merged**
