### PR TITLE
Added info about PoshDotnetDumpAnalyzeViewer

### PR DESCRIPTION
**Pull request by En3Tho**
Hey guys! Do you mind showcasing one more of my Gui.cs based tools? Maybe it's useful to people.

### CODE REVIEW

**Comment by tznind** [comment]
The more the merrier!

Always nice to hear about the tools people are developing.  @tig handles merges but I'm sure he will be excited by this also when he has time to review.

**Comment by En3Tho** [comment]
Thank you! And thanks for the time and energy you spend to maintain this beautiful thing :) I will most certainly move to v2 when it's ready

**Comment by tig** [comment]
You're welcome. 

FWIW, a separate .md file for showcasing Terminal.Gui apps would be neat. It would simplify README.md and make it easier to maintain;update.

E.g. a. `./showcase.md` where each app included 

- Name
- Description
- An animated gif (pulled from an external location)

Any chance you'd want to do a PR for this?

**Comment by En3Tho** [comment]
Yes, I can do this. Not sure about animated gifs though - I guess I can make them fro my apps but not for the others

**Pull request merged**
