### PR TITLE
Stage 1 of #3256 - Prepare Rect for removal

### PR DESCRIPTION
**Pull request by dodexahedron**
## Proposed Changes/Todos

- [x] Renames Rect type
- [x] Changes behavior of ToString and GetHashCode to match BCL type
- [x] Updates Tests that expect strings

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
  - Sorta
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

Here's a PR for the pre-removal work for Rect.

The type still exists, but is renamed to Rectangle and more closely matches behavior of the base class library type.

Next PR, branched from here, actually performs the removal and other necessary changes needed until the other related types are also removed.

This is ready to go. The next one is, as well, and I'll file that after I've run it through the test suite on a couple of different environments.

### CODE REVIEW

**Comment by dodexahedron** [comment]
This is likely to be the biggest PR of this series, since it involved changing `Rect` to `Rectangle` in nearly every file. The other types won't need that kind of renaming dance, so they'll end up touching a lot fewer files. Also, the actual removal of the types should end up touching very few files, as well. Removing Rect definitely touched a whole lot fewer files than this prep work did.

**Review by tig — APPROVED** [review]
LGTM! 

I'd like to merge this after #3249

**Comment by dodexahedron** [comment]
I could have _sworn_ I replied to this, but apparently not. XD

Anyway, I have several more change sets following this one, branched from the last commit of this branch and then from the end of each of those, for the next set.

So that I can keep going without things diverging too much, I'm inclined to merge #3249 into those. I don't imagine there should be any difficult conflicts, since the only touches to files you worked on is the name change from Rect->Rectangle, but rebasing this one on top of that branch or on v2_develop after #3249 is merged will require rebasing the whole tree I've worked on since then, which is a ***lot*** of commits that it annoyingly is making me manually mark resolved even though the resolution is obvious, in a test rebase I just tried.

**Comment by tig** [comment]
@dodexahedron Hopefully the merge conflicts won't be too hard for you to address. As soon as you address them, I'll merge this. Great work.

**Comment by tig** [comment]
> I could have _sworn_ I replied to this, but apparently not. XD
> 
> Anyway, I have several more change sets following this one, branched from the last commit of this branch and then from the end of each of those, for the next set.
> 
> So that I can keep going without things diverging too much, I'm inclined to merge #3249 into those. I don't imagine there should be any difficult conflicts, since the only touches to files you worked on is the name change from Rect->Rectangle, but rebasing this one on top of that branch or on v2_develop after #3249 is merged will require rebasing the whole tree I've worked on since then, which is a _**lot**_ of commits that it annoyingly is making me manually mark resolved even though the resolution is obvious, in a test rebase I just tried.

Shirt. I saw this after I merged #3249. Sorry.

**Comment by dodexahedron** [comment]
Well, since you just merged that one, it's no problem anyway. I was just preparing in case that was going to take a little longer to merge.

I'll go about resolving this now.

**Comment by dodexahedron** [comment]
Hmm... It's not giving me the option to resolve this after that merge. It let me resolve when I made the PR in the first place.

**Comment by dodexahedron** [comment]
Weird. It's not even letting me _see_ the conflicts, on github.

If they're simple enough (they probably are), feel free to do it here. Otherwise, I can do the dance of merge v2_develop -> this branch and push the resolved result.

Whatever you like.

**Comment by dodexahedron** [comment]
Actually strike that. Let me do it like I just said. That'll help avoid any painful rebases on my end.

**Comment by tig** [comment]
image

**Comment by dodexahedron** [comment]
Wow.

Git sure did put up a fight every way I tried to resolve this.

So, I just took the incoming changes, clobbering mine, since they were pretty benign, and am re-applying the necessary changes in follow-up commits. So far, so good. Should be ready shortly.

**Comment by dodexahedron** [comment]
Alrighty. Changes applied and pushed.

Ready to go.

**Comment by dodexahedron** [comment]
> image

Yeah that's all it was showing me. Usually, that button to resolve in-place is available, but it wasn't this time. Oh well. I did it manually on my fork and now it's all set.

**Comment by dodexahedron** [comment]
Woot 🥳

Now to see what I have to do on the branches from that point. Hopefully git will understand a rebate, but I'm afraid it might not, since it's non-linear. I guess I'll find out! 😅

**Pull request merged**
