### PR TITLE
TreeView - (redo) Adds option to highlight only the model text of selected node 

### LINKED ISSUE #2151: TreeView: Mouse wheel scrolls infinitely beyond bottom of items
1PH3RZ7 1

1) Run `Class Explorer` in UI Catalog.
2) Using mouse wheel scroll down. Keep going.

Expected: Scrolling would stop either here:
image

or here (possibly up for debate; ListView does this):
image

(ListView for reference):
image

### PR DESCRIPTION
**Pull request by tig**
This PR:

- Adds new `Style` named `HighlightModelTextOnly` - false by default
- Updates `Class Explorer` Scenario to have a menu for testing new Style
- Updates `TreeViewFileSystem` Scenario to have a menu for testing new Style
- Updates `CollectionNavigator` Scenario to use the new style
- Fixes #2151 

See: https://github.com/gui-cs/Terminal.Gui/pull/2155
See: https://github.com/gui-cs/Terminal.Gui/discussions/2154

IE6jb7x 1

### CODE REVIEW

**Review by tznind — APPROVED** [review]

**Comment by tznind** [comment]
Great stuff! looking really nice.

**Comment by tznind** [comment]
Only one issue I could see is that when using 'colored symbols' the highlight covers the expansion symbol 

image
_Left is normal, right is with `Colored Symbols=true`_

**Comment by BDisp** [comment]
Maybe is the same issue as #2177.

**Review by BDisp — APPROVED** [review]

**Comment by tig** [comment]
> Only one issue I could see is that when using 'colored symbols' the highlight covers the expansion symbol
> 
> image _Left is normal, right is with `Colored Symbols=true`_
> 
> This also stays highlighted when the cursor tabs out of the View:
> 
> image _When `Colored Symbols=true` and `Highlight Model Text Only=true` and focus leaves the `TreeView`_

Fixed:

Tmw5PSI 1

I also changed the Scenario to better / more obviously illustrate any focus issues (iI found some others doing this):

3w9vsN0 1

**Pull request merged**
