### PR TITLE
Fixes #2122. Weird visual artifacts on clearing.

### LINKED ISSUE #2122: Scrolling Scenario: Weird visual artifacts
- Focusing the TextView causes the background color to change to blue
- When it has focus, there's a flickering horizontal bar
- Background changes to black when scrolling horizontally (or vertically)

I don't know if these a bugs in the Scenario or elsewhere.

aFr00WG 1

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2122 - All view size must be cleared.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
I pulled this PR down locally and ran it.

The flickering bar is still there. Was this intended to fix that?

CMP5Yek 1

**Comment by BDisp** [comment]
Yes I've got that now. I also check Character Map scenario is blank. The fix corrupt other situations. We have to see the best solution for this.

**Comment by BDisp** [comment]
@tig what is causing the flickering is the `horizontalRuler` label of the `Scrolling` scenario. If you set the Height = 1 the flickering issue stops. This issue only happens with the `WindowsDriver`.

**Comment by tig** [comment]
I merged this PR down locally and I see this issue in the Class Explorer scenario as well. 

WcXYhB7 1

**Comment by BDisp** [comment]
@tig can you confirm if that happens with the others drivers? Mine is working well with `WindowsDriver` on `Windows Terminal`.

view-clear-fix

**Comment by tig** [comment]
Just tested with `-usc` and I get the same issue.

Can you please fix the merge conflicts in this PR so I can pull it down again and double check again?

**Comment by BDisp** [comment]
> Just tested with `-usc` and I get the same issue.
> 
> Can you please fix the merge conflicts in this PR so I can pull it down again and double check again?

Done @tig. I hadn't realized the conflicts. Thanks.

**Pull request merged**
