### PR TITLE
Fixes #2022. ScrollBarView doesn't show the down arrow on vertical if there isn't horizontal.

### LINKED ISSUE #2022: ScrollBarView doesn't show the down arrow on vertical if there isn't horizontal.
This is a tes▲
 This is a tes┬
 This is a tes┴
 This is a tes░
 This is a tes░
 This is a tes

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2022 - The `contentBottomRightCorner` was always drawing over the down arrow.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
@BDisp I'm afraid my latest merges caused a conflict here. Can you resolve?

**Comment by BDisp** [comment]
> @BDisp I'm afraid my latest merges caused a conflict here. Can you resolve?

Did you made this change? I'm getting an error:

imagem
imagem

**Comment by tig** [comment]
> > @BDisp I'm afraid my latest merges caused a conflict here. Can you resolve?
> 
> Did you made this change? I'm getting an error:
> 
> imagem imagem

I don't think I did. I am super confused myself!

**Comment by BDisp** [comment]
In my commit https://github.com/gui-cs/Terminal.Gui/pull/2023/commits/e8ef793b05a9cf6e6dcccd42795d2d0fdd569e5e I only reformat that. But you did a revert and now the develop branch is different:
```

		public void ClearKeybinding (Command command)
		{
			foreach (var kvp in KeyBindings.Where (kvp => kvp.Value.SequenceEqual (command)).ToArray ()) {
				KeyBindings.Remove (kvp.Key);
			}
		}

```

**Comment by BDisp** [comment]
In my commit https://github.com/gui-cs/Terminal.Gui/pull/2023/commits/e8ef793b05a9cf6e6dcccd42795d2d0fdd569e5e I only reformat that. But you did a revert and now the develop branch is different:
```

		public void ClearKeybinding (Command command)
		{
			foreach (var kvp in KeyBindings.Where (kvp => kvp.Value == command).ToArray ()) {
				KeyBindings.Remove (kvp.Key);
			}
		}

```

**Comment by BDisp** [comment]
Here it is https://github.com/gui-cs/Terminal.Gui/pull/2027/commits/a8b7f9491c3561303dccfc3b80f1b549dd3e5c24

**Comment by tig** [comment]
How did I do that? Arrg. 

So sorry.

Can you easily tell what the correct way to fix this is?

**Comment by BDisp** [comment]
I think the better accurate way is doing a reset keeping the changes. Then you create a new PR with the equal to the original. I think doing a revert on a reverted commit all the changes are lost. So do a reset keeping the changes.


> How did I do that? Arrg.
> 
> So sorry.
> 
> Can you easily tell what the correct way to fix this is?

**Comment by BDisp** [comment]
If you already other commits after the reverted commit the reset isn't a good solution, because it will undo all the commits above. I'm googling about the better way :-)

**Comment by tig** [comment]
I have no idea where the `vp.Value.SequenceEqual` thing came from.

I've gone back and looked at the `v1.7.x` tags and that code was not there! What PR introduced this?

Is this the only line that is screwed up?

**Comment by BDisp** [comment]
> Is this the only line that is screwed up?

No, this PR was rebase from a wrong develop branch and that why this it having errors.

**Comment by tig** [comment]
Would it be possible for you to recover the changes you meant for this PR from your local repo, create a new branch, and push a new PR?

**Comment by BDisp** [comment]
> @BDisp Would it be possible for you to recover the changes you meant for this PR from your local repo, create a new branch, and push a new PR?

I'll try to found some original branch which I can recover with the latest changes.

**Comment by BDisp** [comment]
I already did with the latest branch which was already merged in PR #2026 and I still get this conflicts. I also doesn't seen in the develop branch the "ReflectionTools.cs" file which was merged with the PR #2000.
The changes in the `View.ClearKeybinding` was merged on the PR #1966.
I don't know what more I have to do.

**Comment by BDisp** [comment]
> @BDisp Would it be possible for you to recover the changes you meant for this PR from your local repo, create a new branch, and push a new PR?

I already tried create a new branch to push a new PR, but result in one unchanged branch because indeed this changes were already merged no the PR #2020 to avoid unit test failure with the `ScrollBarView` on the `ViewTests`. The main problem now is the branch `develop` is screwed up. So I will close this PR because it was already merged and will be updated after the `develop` branch is fixed.

**Comment by BDisp** [comment]
Here is a print screen of all files that were changed with news PR's after the PR #2020 was merged:

imagem
imagem
imagem

**Comment by BDisp** [comment]
I think I discovery the culprit of the `develop branch` mess up. Is in the PR #2027 on the commit https://github.com/gui-cs/Terminal.Gui/pull/2027/commits/a45314e4a9e6e3e0d1869c0e17cf1aa52abac9f3.
Probably you merged from from main to develop branch with old content in the commit https://github.com/gui-cs/Terminal.Gui/pull/2027/commits/959f8b3742b3310e775fe63fb2e5ea8f3a1d9c51.

**Comment by tig** [comment]
Bummer.

I won't be able to work on this until Sunday at the earliest!

**Pull request closed without merging**
