### PR TITLE
Fixes #3420 (partial) - Adding PowerShell modules and initial Analyzer projects

### LINKED ISSUE #3420: Add internal analyzers and source generators
Implementing some internal analyzers and source generators for Terminal.Gui that add enhanced functionality to specified code elements in a standard and high-performance way.

Right now, the only functional generator is one for enum types that adds high-performance extension methods as alternatives to IsDefined and conversions to int and uint. More are planned and in progress, but I wanted to go ahead and file this issue now that it's in a useable state.

There is also an included PowerShell module that exposes an `Update-Analyzers` commandlet that rebuilds the analyzers, since visual studio can't dynamically reload analyzers that have already been loaded. It provides optional switches to automatically close running VS processes with Terminal.sln opened, re-launch the solution upon completion, output fewer informational messages, and to run without interactive prompting - all of which default to off. This makes it really convenient to take care of that tedious process whenever changes are made to analyzer/generator code. Running it as `Update-Analyzers -Force -AutoLaunch -AutoClose` will, without further prompting, close the VS processes, remove the obj and bin folders in the Terminal.Gui and Terminal.Gui.Analyzers.Internal project directories, build the analyzers in both Debug and Release configurations, and then re-load Visual Studio with Terminal.sln.

### PR DESCRIPTION
**Pull request by dodexahedron**
Initial PR for analyzer work.

This adds PowerShell modules for use when developing Terminal.Gui. Future enhancements are planned and suggestions are more than welcome.

Analyzer projects are in this PR but the projects are not included in the solution yet, nor referenced by any other projects in the solution.

This PR is ready to go as-is, or I can add the solution and project file changes to wire it all up before merge if desired.

## Proposed Changes/Todos

- [x] Add powershell modules/scripts to perform routine operations when developing Terminal.Gui.
  - [x] Terminal.Gui.PowerShell module: Environment and solution functionality.
    - [x] Open-Solution: Launches the Terminal.sln file
    - [x] Close-Solution: Closes running devenv.exe processes with Terminal.sln loaded
    - [x] Set-Environment: Sets up a standard environment for script execution, in a temporary session.
    - [x] Reset-Environment: Undoes changes made by Set-Environment or just exits the inner session, if requested.
  - [x] Terminal.Gui.PowerShell.Analyzers module: Functionality related to analyzer projects.
    - [x] Build-Analyzers: Builds analyzer projects in Debug and Release mode, with additional functionality exposed via switch parameters.
- [x] Add analyzer project with basic enum extension analyzer and generator
- [x] Add test project for the analyzer project
- [x] Add debug project for the analyzer project

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
  - Well... It's PowerShell, so it's different, but it's pretty similar. 
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `<# #>` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by dodexahedron** [comment]
There we go. Now it's ready. :)

**Comment by dodexahedron** [comment]
Some future additions I've considered so far and may add at some point:

 - Build, clean, and test functionality for the solution and maybe also for specific projects, to ensure consistent builds.
 - Helpers for standard git operations, like branching for an Issue and stuff like that.
 - Running the JetBrains formatter tool on changed files (as reported by git, in the current branch), maybe? And maybe fetching it if it isn't already available locally?

**Comment by dodexahedron** [comment]
Actually... This does include part of the analyzer projects, too. I'll rename accordingly.

**Comment by dodexahedron** [comment]
Updated to match what's actually contained in the PR.

I haven't pushed the solution and other csproj file changes to use the analyzers, in this PR, for a couple of reasons:
 - So everyone else can at least build them and make sure that works in their environments.
 - I want to make some more changes to the analyzers before we include them in the pipeline.

If those are unimportant to y'all, and you'd rather I just wire them up now, I'll be happy to do so. Otherwise, that'll come in a separate PR when it's ready.

**Review by tig — COMMENTED** [review]
Please add README.md's to `./Scripts` and `./Analyzers` explaining their purpose and how they are used.

**Comment by tig** [comment]
I've tried to read all your posts on these things, but I suck at learning by just reading. I need to party on the code.

How do I use all this stuff "in anger"?

**Comment by dodexahedron** [comment]
> Please add README.md's to `./Scripts` and `./Analyzers` explaining their purpose and how they are used.

No problemo. Will do this evening most likely.

> I've tried to read all your posts on these things, but I suck at learning by just reading. I need to party on the code.
> 
> How do I use all this stuff "in anger"?

No worries. That's part of why I didn't go ahead and include it in the solution yet.

### Visual Studio problems with Roslyn projects
Visual Studio's Roslyn host is still a .net framework host (why it's netstandard2.0 required) and can't unload one once it's loaded. That has two main impacts:
 - The first load of the solution from a fresh or `dotnet clean`ed state will be oddly and unfixably broken. Have to build the roslyn projects and reload VS.
 - If you make any changes to the Roslyn project code that you want to then use outside of the associated "Debug" project, you also need to rebuild them and reload VS.

That's not reload the solution - any VS process with the solution or the Terminal.Gui.csproj opened have to be closed to unload the old assemblies.

### Scripts to the rescue!
That's where the scripts came in - to simplify that.

I wanted to turn that multi-step process into as few as possible. And we're dotnet and it appears a powershell script was at least prototyped at some point in the repo, plus PS is a full and cross-platform dotnet environment, so PS is natural all around.

So I got it down to just a single command that kicks it all off.

And then, through some combination of wanting to be flexible, wanting to write good scripts, wanting to make it easy, wanting to make it re-usable, and some good old-fashioned going a bit overboard, I make them modules, with the intent of adding more over time, including a new build function, which there's a non-working prototype definition of in the current code I have, for people to play around with.

I might even throw up a private PSRepository to mirror the current modules, but signed so PowerShell doesn't complain without you having to `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`.

### More to come
I've actually got even more sprucing up of those, as well, that I'll push into this PR, as well as the requested markdown files.

I went back and re-did some things that organically outgrew their original quick-and-dirty versions, and which no longer fit how I ended up having them all formally defined and organized. So now they are consistent and follow recommendations and literal [requirements](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/required-development-guidelines?view=powershell-7.4) for powershell (some of which actually are hard requirements and others of which are just cardinal sins), as well as gained some more features and flexibility while I was at it.

Now just import the module and then run whatever commands you want that it exports.

### How to use for the source generators
If you already have VS open, that's fine. The script can close it if it was launched with Terminal.sln or currently has Terminal.sln loaded.

Open powershell. Must be PS Core, version 7.4.0 or higher (current is 7.4.2 but that doesn't matter). If you don't know how to check, don't worry. The modules will validate the environment on attempt to import.

Navigate to your repo directory in the powershell session, and into the Scripts directory.

Run this, to import all currently-defined and exported modules and their dependencies.
```powershell
Import-Module ./Terminal.Gui.PowerShell.psd1
```

Notice that your prompt will have been slightly modified to indicate you're in our modified environment. No environment changes are permanent. When you Remove the module, call a certain function, or just close the session, the prompt and anything else changed when importing the modules will be back to their original states.

### Now play!
You can get the list of Terminal.Gui modules and available commands loaded in the current session with:
```powershell
Get-Command -Module Terminal.Gui.PowerShell
```

To get full help for any command, run `Get-Help CommandName` with or without optional switches for mor info like `-Full`, `-Detailed`, and `-Examples`. `-Full` is everything including all others.\
Example:
```powershell
Get-Help New-GitBranch -Full
```
```plaintext
TGPS V:\repos\Terminal.Gui\Scripts> Get-Help New-GitBranch -Full

NAME
    New-GitBranch

SYNOPSIS
    Creates a new branch with the specified name.


SYNTAX
    New-GitBranch -Name <String> [-Push] [-WhatIf] [-Confirm] [<CommonParameters>]

    New-GitBranch -Name <String> -Push [-Remote <String>] [-WhatIf] [-Confirm] [<CommonParameters>]

    New-GitBranch -Name <String> -NoSwitch [-WhatIf] [-Confirm] [<CommonParameters>]


DESCRIPTION
    Creates a new branch with the specified name.


PARAMETERS
    -Name <String>
        The name of the new branch.
        Always required.
        Must match the .net regex pattern "v2_\d{4}_[a-zA-Z0-9()_-]+".
        Must also otherwise be a valid identifier for a git branch and follow any other project guidelines.

        Required?                    true
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -NoSwitch [<SwitchParameter>]
        If specified, does not automatically switch to your new branch after creating it.
        Default is to switch to the new branch after creating it.

        Required?                    true
        Position?                    named
        Default value                False
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -Push [<SwitchParameter>]
        If specified, automatically pushes the new branch to your remote after creating it.

        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -Remote <String>
        The name of the git remote, as configured.
        If you never explicitly set this yourself, it is typically "origin".
        If you only have one remote defined or have not explicitly set a remote yourself, do not provide this parameter; It will be detected automatically.

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -WhatIf [<SwitchParameter>]

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -Confirm [<SwitchParameter>]

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).

INPUTS
    None


OUTPUTS
    The name of the current branch after the operation, as a String.
    If NoSwitch was specified and the operation succeeded, this should be the source branch.
    If NoSwith was not specified or was explicitly set to $false and the operation succeeded, this should be the new branch.
    If an exception occurs, does not return. Exceptions are unhandled and are the responsibility of the caller.


NOTES


        Errors thrown by git commands are not explicitly handled.
```

All commands have kinda excessive help defined. Side note: I like how they do it in pseudo-mandoc style.

And the above example is in the code I have now (not pushed yet), and will do exactly what it says. Makes a new branch with the specified name, enforcing the v2_####_etc naming restriction, and pushes it to your remote. Or modifications to that behavior as described in the help, and from what I hope are pretty obviously-named parameters in the first place.

And remember PS does tab completion, and any of these that have parameters will help you as much as they can with that.

When I push again, all of the currently-defined commands will be in a working state.

Right now, that list is:
```powershell
TGPS V:\repos\Terminal.Gui\Scripts> get-command -Module Terminal.Gui.PowerShell
```
```plaintext
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Build-Analyzers                                    1.0.0      Terminal.Gui.PowerShell
Function        Build-TerminalGui                                  1.0.0      Terminal.Gui.PowerShell
Function        Close-Solution                                     1.0.0      Terminal.Gui.PowerShell
Function        New-GitBranch                                      1.0.0      Terminal.Gui.PowerShell
Function        Open-Solution                                      1.0.0      Terminal.Gui.PowerShell
```


With the code currently pushed, you can use the Build-Analyzers command, already. It's just a more messy environment, so hang tight for a little bit while I write up some basic README.md files and at least prototype the Build-TerminalGui command beyond just an empty method.

Alrighty. Back to it.

**Comment by dodexahedron** [comment]
Oh another thing to mention up front:

Since these are intended mostly for our benefit at dev time, I don't have particular interest in supporting a wide range of environments.

Thus, the module manifests require that it is PS Core, Version 7.4.0 or higher, and the host process must be ConsoleHost. That means it is running in a terminal and not hosted within some other application, because that just opens up a ton of stuff to deal with that isn't important for us and can be worked around by simply running pwsh from within whatever that is.

For example, attempting to import the module from a powershell panel inside VS Code results in this:
```plaintext
Import-Module: The name of the current PowerShell host is: 'Visual Studio Code Host'. The module 'V:\repos\Terminal.Gui\Scripts\Terminal.Gui.PowerShell.psd1' requires the following PowerShell host: 'ConsoleHost'.
```

ConsoleHost is what pwsh identifies itself as no matter what it is running in.

So, simply calling `pwsh` first, before `import-module`, is acceptable to powershell.

**Comment by dodexahedron** [comment]
A little light reading... 😅

**Comment by tig** [comment]
Makes sense. I think. 

For normal dev I won't have to use the scripts, right? Only if I need to modify the analyzers?

**Comment by dodexahedron** [comment]
Right. They're just for convenience and for the analyzers.

First time using them, once added to solution, you'll just run Build-Analyzers

Only have to call that again if you change them or accidentally clean the solution or basically anything that would alter the assemblies produced by the analyzer projects.

**Comment by dodexahedron** [comment]
I just pushed a partial update that includes the reorg, a README.md in the Scripts directory, and everything but Build-TerminalGui currently functional.

Build-TerminalGui just writes output saying it doesn't work yet. But it's still testable in terms of invocation/parameters/whatev.

**Comment by dodexahedron** [comment]
I've tested these on Ubuntu 23.10 and Windows 11 Enterprise, so far.

They do what I intend them to do, but I wrote them, so what made sense to me may or may not make as much sense to someone else.

So feedback more than welcome for sure.

**Comment by dodexahedron** [comment]
Side note not for this PR:

I usually also provide a Makefile for convenience and comfort of Linux users, for these sorts of things, that essentially just wrap the same stuff so that those used to just running `make` can do what they're used to and those from dotnet land can use what they are used to.

I'll probably write those like... way down the line, closer to release time.

**Pull request merged**
