### PR TITLE
Fixes #3095. WindowsDriver should return the mask keys to IsShift, IsAlt and IsCtrl return the right value.

### LINKED ISSUE #3095: WindowsDriver should return the mask keys to IsShift, IsAlt and IsCtrl return the right value.
If only the `ShiftKey`, `AltKey` or `CtrlKey` are used the `Key.IsShift`, `Key.IsAlt` or `Key.IsCtrl` returns false and should return true.

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #3095 - The drivers should use the mask keys before create a `Key` object.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
If the user just presses and releases a shift key it should be registered as just that key. 

This change breaks this.

**Comment by BDisp** [comment]
> If the user just presses and releases a shift key it should be registered as just that key.
> 
> This change breaks this.

A shift key pressed or released is always a shift key. If you check the `wVirtualKeyCode` is the same at key down and key up. I don't understand what it is breaking (`16`).

Captura de ecrã 2023-12-28 161548

Captura de ecrã 2023-12-28 161657

**Comment by BDisp** [comment]
If you are meaning that must returns as `16` the `IsShift` never return true. I think you are misunderstood something here.

**Comment by tig** [comment]
Run the Key scenario. Press ctrl and release it.

**Comment by BDisp** [comment]
The issue is because the `Key` class is removing the `KeyCode.ShiftMask` on all situations. The only situation where it must remove the `KeyCode.ShiftMask`, if it's the only modifier key used, is when it's handling a printable character where only the character must be passed. For e.g. `TextView` cannot handle `KeyCode.A | KeyCode.ShiftKey` and thus it only needed the `KeyCode.A`. So the solution is if only the modifiers keys are pressed without another key then they must be handled in the `Key` class as `KeyCode.ShiftMask`, `KeyCode.AltMask`, `KeyCode.CtrlMask` or as `KeyCode.ShiftKey`, `KeyCode.AltKey`, `KeyCode.CtrlKey`.
I'll try to discover some solution for this.

**Comment by tig** [comment]
I think you're wrong but I cannot yet articulate why. 

Please give me a few days to get a chance to dive in. 

I'm traveling internationally next few days.

**Comment by BDisp** [comment]
> I think you're wrong but I cannot yet articulate why.
> 
> Please give me a few days to get a chance to dive in.
> 
> I'm traveling internationally next few days.

No problem, sorry. I only will add my solution and you only accept it after you have time and if you agree with it, of course.

**Comment by BDisp** [comment]
It's working now. Modifiers key must be valid for key down and key up.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/12c3a10e-f4bb-4cbb-a1a3-f1dc723f4809

**Comment by tig** [comment]
Closing this as it's addressed in your other pr.

**Pull request closed without merging**
