### PR TITLE
Fixes #1465.  TableView columns can now be hidden via `ColumnStyle.Visible`

### LINKED ISSUE #1465: Add 'Visible' property to ColumnStyle in TableView
This is a new ticket to come out of https://github.com/migueldeicaza/gui.cs/issues/1463 (I've created a new ticket since that one is closed and was more general).

It is to add the ability to hide columns in TableView:

> I think a better solution would be to add a Visible property to the ColumnStyle class. I can look into this, it should be reasonably easy.

### PR DESCRIPTION
**Pull request by tznind**
Fixes #1465 - TableView columns can now be hidden via `ColumnStyle.Visible`

Changes made to `TableView` so far:

- `IEnumerable<ColumnToRender> CalculateViewport` does not return invisible columns
- Added `private int GetNearestVisibleColumn (int columnIndex, bool lookRight)` 

The new method should be used up front wherever possible to adjust input parameters ahead of the rest of the consumer method executing.  This should be the most maintainable way of implementing this feature and prevent us having to check for invisible columns all over the place.

TODO:

- [x] Simple keyboard navigation skips invisible columns
   - [x] Test arrow keys
   - [x] Test first/last column invisible
   - [x] Test Home/End
- [x] Test behaviours when no columns are visible matches when no `Table` is set.
- [x] Rendering
  - [x] Invisible columns are not rendered
  - [x] Test first/last column invisible renders all line seperators correctly
  - [x] `ShowHorizontalScrollIndicators` should not render when the 'scrollable to' columns are invisible
- [x] public API
  - [x] Test `EnsureValidSelection` considers column visibility
  - [x] Test `EnsureSelectedCellIsVisible` considers column visibility
  - [ ] ~Test `EnsureValidScrollOffsets`  considers column visibility~
- [x] Add a Scenario
  - [x] Wait for https://github.com/gui-cs/Terminal.Gui/pull/2239 then update `TableEditor` scenario so user can right click a header and hide it (via context menu)
  - [x] Add a ShowAllColumns menu option to get them all back again
- [ ] Multi selection (rectangular selection)
  - [x] Ensure shift+arrow extends over invisible columns
  - [x] Ensure invisible columns are not returned in `GetAllSelectedCells`
  - [ ] ~Ensure `MultiSelectedRegions` / `TableSelection.Rect` does not have a boundary lying on invisible column~*

_\* I don't think we want to make changes to the selection just because a column becomes invisible, it might get 're visibled' later.  User can always clear the selection when making this change if they want anyway.  I think it is enough for keyboard/mouse navigation not to select the cells and not return them in `GetAllSelectedCells`_

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
@tig if you are able to find the time to please review #2239 then once its merged I can take `main` and finish this PR by adding a header right click context menu to the TableEditor scenario for more complete user testing of this feature (Show/Hide columns).

**Comment by tznind** [comment]
Have marked as ready to review now and added the new scenario functionality:

show-hide
_Show/Hide context menu for TableEditor _

**Comment by tznind** [comment]
CI error does not seem to be related to my changes:

```
The active test run was aborted. Reason: Test host process crashed : bash: line 1: xclip: command not found
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminal.Gui.DirListView.Watcher_Error(Object sender, ErrorEventArgs e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Windows/FileDialog.cs:line 119
   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents()
```

**Comment by BDisp** [comment]
This is causing by the `System.IO.FileSystemWatcher` which is already fixed on the `develop` branch. If you merge you'll see that CI error doesn't reproduce.

**Review by tig — APPROVED** [review]

**Pull request merged**
