### PR TITLE
ListView: add support for multi-line items

### PR DESCRIPTION
**Pull request by migueldeicaza-msft**
Better version that supports multi-line ListView items.

In this example, a custom renderer draws two-line items, and requires ListView.ItemHeight to be set to 2:

image

### CODE REVIEW

**Comment by migueldeicaza-msft** [comment]
Observation: perhaps we could make it so that ListWrapper has support for rendering multi-line text, so that folks do not need to implement a custom renderer for simple scenarios.

The RenderUstr could look for '\n' and use that to wrap around the text.

**Comment by cssmismi** [comment]
In the demo picture above, after selecting C: and hitting the up arrow, the contents of the lists changes and only 1 ListView item is visible.

**Review by tig — CHANGES_REQUESTED** [review]
This is great. 

All new features require two things missing from this PR though:

1) Unit tests
2) Sample code in a Scenario in UI Catalog. We are trying to deprecate demo.cs as it unstructured and doesn't scale as a way to discover samples.

Thanks.

**Comment by tig** [comment]
@migueldeicaza now that you have tons of time on your hands 😉, wanna look at the changes requested here so we can merge this?

**Comment by tig** [comment]
> @migueldeicaza now that you have tons of time on your hands 😉, wanna look at the changes requested here so we can merge this?

I can't merge this until the requested changes are made...

**Comment by tig** [comment]
> > @migueldeicaza now that you have tons of time on your hands 😉, wanna look at the changes requested here so we can merge this?
> 
> I can't merge this until the requested changes are made...

@migueldeicaza - what's the chance you'll be able to address this anytime soon? Would you prefer one of the other maintainers take it on? I'd like to get this merged!

**Comment by migueldeicaza** [comment]
Happy to let someone look at it.  I need to setup a .net development system again :-)

**Comment by tig** [comment]
> Happy to let someone look at it. I need to setup a .net development system again :-)

I understand. I'll see if I can dive into this today.

**Comment by tig** [comment]
Dug in a little and this PR is far from ready:

- Issue @cssmismi pointed out above about selecting last item in list causing weird scroll behavior
- Demo code does not exercise code enuf to know it's all working. E.g. only 3 items and no scrolling. Are we sure scrolling is working?
- Mouse selection doesn't work right
- Needs demo code moved to a UI Catalog scenario
- No new unit tests

I'm going to mark this PR as draft. Hopefully myself or someone will find the time to address it.

**Comment by BDisp** [comment]
For now I have this like the image bellow but I want to add more features, like header, multi-columns, column alignment and row alignment. 

listview-multine-feature

**Comment by tig** [comment]
Ancient. closing.

**Pull request closed without merging**
