### PR TITLE
Fixes #3687. ColorPicker isn't respecting the current UI culture.

### LINKED ISSUE #3687: ColorPicker isn't respecting the current UI culture.
That why actually some unit tests are failing.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3687

## Proposed Changes/Todos

- [x] Replace with CurrentUICulture

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — APPROVED** [review]
Is there a way to have unit tests validate this so these mistakes (which I made) are ALWAYS caught?

**Comment by BDisp** [comment]
> Is there a way to have unit tests validate this so these mistakes (which I made) are ALWAYS caught?

You didn't make any mistakes. Who made the mistake was me when I accepted the PR, sorry. I think, due the fact no more errors were caught it meaning that all the rest is correct. The issue was the mouse event was always running while the `MouseGrabView` is null and view not null, resulting the event propagating to the upper hierarchy. My apologies.

**Comment by BDisp** [comment]
> Is there a way to have unit tests validate this so these mistakes (which I made) are ALWAYS caught?

I think the failing unit test is enough. But I think there will be have problems if the user creates a custom culture other the `en` by not having available resources strings, resulting in a empty color names.

**Comment by tig** [comment]
> > Is there a way to have unit tests validate this so these mistakes (which I made) are ALWAYS caught?
> 
> I think the failing unit test is enough. But I think there will be have problems if the user creates a custom culture other the `en` by not having available resources strings, resulting in a empty color names.

It did not fail for me. It fails for you because you don't use `en`.

**Comment by BDisp** [comment]
> It did not fail for me. It fails for you because you don't use `en`.

For this reason I think that all unit tests that uses resource string should have a non `en` culture. I propose `pt` if it's ok with you. Also I think they must fallback to the `en` culture if they wasn't yet translated for an existing resource.

**Pull request merged**
