### PR TITLE
Add Game using Terminal.gui called "Capital and Cargo" to showcase.md

### PR DESCRIPTION
**Pull request by dhorions**
My 12 year old son and I built a game using Terminal.gui.
I believe it would be a good candidate to be on the Showcase list of this project.
If you agree, please approve this pull request, but if you don't, that is also fine.

## Changes
Add https://github.com/dhorions/Capital-and-Cargo to showcase.md

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [X] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [X] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [ ] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any poor grammar or misspellings
- [X] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
WOW!

I love this. I only played for a few minutes, but it's addicting.

Kudos to your son (and you)!

It would be killer if you could port this to v2 asap so we have another real-world test case of all the new APIs.

**Review by tig — APPROVED** [review]

**Comment by dhorions** [comment]
> It would be killer if you could port this to v2 asap so we have another real-world test case of all the new APIs.

I haven't looked into the differences with v2, will it be a lot of rework you think?
Is there some kind of conversion documentation?

**Comment by tig** [comment]
> > It would be killer if you could port this to v2 asap so we have another real-world test case of all the new APIs.
> 
> I haven't looked into the differences with v2, will it be a lot of rework you think? Is there some kind of conversion documentation?

Actually, if you're interested maybe what I'll do is submit a PR to your repo and do the porting myself.

This will help me flush out the docs!

**Comment by dodexahedron** [comment]
Love it!

**Comment by dhorions** [comment]
> > > It would be killer if you could port this to v2 asap so we have another real-world test case of all the new APIs.
> > 
> > I haven't looked into the differences with v2, will it be a lot of rework you think? Is there some kind of conversion documentation?
> 
> Actually, if you're interested maybe what I'll do is submit a PR to your repo and do the porting myself.
> 
> This will help me flush out the docs!
> 
> 
That is a great idea. What do you think @dasmehe

**Comment by dasmehe** [comment]
I

> > > > It would be killer if you could port this to v2 asap so we have another real-world test case of all the new APIs.
> > > 
> > > 
> > > I haven't looked into the differences with v2, will it be a lot of rework you think? Is there some kind of conversion documentation?
> > 
> > 
> > Actually, if you're interested maybe what I'll do is submit a PR to your repo and do the porting myself.
> > This will help me flush out the docs!
> 
> That is a great idea. What do you think @dasmehe

I like it!

**Pull request merged**
