### PR TITLE
Fixes #3418. TextFormatter bugs.

### LINKED ISSUE #3418: `TextFormatter` bugs
This API is described as:

```cs
    /// <summary>
    ///     Returns the number of columns in the widest line in the list based on the <paramref name="startIndex"/> and
    ///     the <paramref name="length"/>.
    /// </summary>
    /// <remarks>
    ///     This API will return incorrect results if the text includes glyphs who's width is dependent on surrounding
    ///     glyphs (e.g. Arabic).
    /// </remarks>
    /// <param name="lines">The lines.</param>
    /// <param name="startIndex">The start index.</param>
    /// <param name="length">The length.</param>
    /// <param name="tabWidth">The number of columns used for a tab.</param>
    /// <returns>The maximum characters width.</returns>
    public static int GetWidestLineLength (
        List<string> lines,
        int startIndex = -1,
        int length = -1,
        int tabWidth = 0
    )
```

Based on this, this unit test should pass. It doesn't. The actual width returned is `1`.

```cs
    [Theory]
    [InlineData (new [] { "0123456789" }, 10)]
    public void GetWidestLineLength_List_GetsWidth (IEnumerable<string> text, int expectedWidth
    )
    {
        Assert.Equal (expectedWidth, TextFormatter.GetWidestLineLength (text.ToList ()));
    }
```

I'm massively confused. Perhaps the API docs are completely wrong?

@BDisp can you advise?

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3418

## Proposed Changes/Todos

- [x] Fix somes bugs on calling GetWidestLineLength method
- [x] Allowing resetting alignments when justify checkbox is checked on the TextAlignmentsAndDirections scenario
- [x] Add unit tests for multiline justified horizontal and vertical

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
Horizontal:

image

Vertical:

image

Horizontal Justified:

image

Vertical Justified:

image

Horizontal without wrap:

image

Vertical without wrap:

image

Horizontal with wrap:

image

Vertical with wrap:

image

Horizontal Justified with wrap:

image

Vertical Justified with wrap:

image

Horizontal with wrap and 2 lines:

image

Vertical with wrap and 2 lines:

image

The horizontal and vertical justified behavior with word wrap is considered the left and top alignments respectively, for obvious reason, of course.

**Comment by BDisp** [comment]
@tig I fixed the issue you mentioned on the https://github.com/gui-cs/Terminal.Gui/issues/3418#issuecomment-2080803449. Maybe it help you with your PR. Cheers.

**Comment by BDisp** [comment]
@tig shouldn't labels respect new lines? Or am I mistaken? Notice that there is a new line between the two words.

image

**Comment by tig** [comment]
Yes, if Text has new lines in it, they should be respected.

**Comment by tig** [comment]
I am not going to spend any time looking at this PR. 

If you want to continue to use it, please mark it as draft.

**Pull request closed without merging**
