### PR TITLE
Fixes #2649 - Unit Tests on Windows are failing

### LINKED ISSUE #2649: Unit Tests are failing on Windows on `v2_develop` branch
Something weird with `WindowsClipboard`. 

image

I'm running this down now.

### PR DESCRIPTION
**Pull request by tig**
Fixes #2649 

I think.

### CODE REVIEW

**Comment by BDisp** [comment]
Good catch. I removed many `ToString()` while I was working on the PR but many stayed :-)

**Comment by tig** [comment]
Arrrg...

```
> dotnet clean
> dotnet test

...

[xUnit.net 00:00:46.12]     Terminal.Gui.ViewsTests.TextViewTests.HistoryText_Undo_Redo_Copy_Without_Selection_Multi_Line_Paste [FAIL]
  Failed Terminal.Gui.ViewsTests.TextViewTests.HistoryText_Undo_Redo_Copy_Without_Selection_Multi_Line_Paste [55 ms]
  Error Message:
   Assert.Equal() Failure
           (pos 0)
Expected: This is the first line.\r\nThis is the firs···
Actual:   \r\nThis is the first line.\r\nThis is the se···
           (pos 0)
  Stack Trace:
     at Terminal.Gui.ViewsTests.TextViewTests.HistoryText_Undo_Redo_Copy_Without_Selection_Multi_Line_Paste() in C:\Users\charlie\s\gui-cs\Terminal.Gui\UnitTests\Views\TextViewTests.cs:line 4676
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Failed!  - Failed:     1, Passed:  2263, Skipped:     0, Total:  2264, Duration: 1 m 40 s - UnitTests.dll (net7.0)
NativeCommandExitException: Program "dotnet.exe" ended with non-zero exit code: 1.
```

**Comment by tig** [comment]
With `v2_develop` I get even more failures.

**Comment by BDisp** [comment]
@tig I pulled your PR and none of the unit test are failing. Please close VS2022 and kill any process running int the `C:\Program Files\Microsoft Visual Studio\2022`.

**Comment by tig** [comment]
> @tig I pulled your PR and none of the unit test are failing. Please close VS2022 and kill any process running int the `C:\Program Files\Microsoft Visual Studio\2022`.

I REBOOTED! :-)

**Comment by BDisp** [comment]
> I REBOOTED and still got failures.

Ah so I think you have to send the laptop to trash :-)

**Pull request merged**
