### PR TITLE
Fixes #2587 - Add CheckBoxTableSourceWrapper for TableView checkboxes

### LINKED ISSUE #2587: TableView: Multi-select with marked indicator?
I just realized TableView is mising something I just assumed was there, @tznind please correct me if i'm wrong....

`Out-ConsoleGridView` provides `-OutputMode Multiple`. 

oLBeFvu 1

When I port it to be based on `TableView` I'll need similar functionality.

It appears there is no way to have the first column (or something to the left of the 1st column) be a "marked" indicator.

Probably not super important, because multi-select where the selected rows are inverted does the trick. I think.

### PR DESCRIPTION
**Pull request by tznind**
Fixes #2587 - Adds a new TableView data source designed to wrap another and append a checkbox column to the start.

Some things to note:
- The new column counts for styles etc.  So if you hide column 0 then add checkboxes wrapper and don't update your style then the first column of your data will re-appear and the checkboxes will be hidden.
- If you have a sort routine that re-orders rows then you have to also re-order the checkboxes if you want to preserve item checkedness.

table-checkboxes

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
@tig can you please test the UX of this and provide guidance on any changes you would like to make it more consistent with listview.

**Comment by tig** [comment]
> @tig can you please test the UX of this and provide guidance on any changes you would like to make it more consistent with listview.

Will do!

**Comment by tig** [comment]
The only thing I noticed is `ListView` supports marking with single selection and uses the radio style mark for that. 


```ps
ls | out-console-grid-view -outputmode Single
```

UyJcATx 1

**Comment by tznind** [comment]
I've refactored the checkbox wrapper to now allow checking by object delegates (the index/row version remains).

This is more useful if you want to have a dynamic table (e.g. filtering and sorting) and don't have to want to have to manage syncing the indexes yourself:

```csharp
// Create some objects
var pets = new List<PickablePet> {
	new PickablePet(false,"Tammy","Cat"),
	new PickablePet(false,"Tibbles","Cat"),
	new PickablePet(false,"Ripper","Dog")
};

// Tell TableView how to represent the objects (which columns)
var source = new EnumerableTableSource<PickablePet> (
	pets,
	new () {
		{ "Name", (p) => p.Name},
		{ "Kind", (p) => p.Kind},
	});

// Create checkbox wrapper that stores 'toggled' state in the IsPicked property of the pet
var withCheckboxes = new CheckBoxTableSourceWrapperByObject<PickablePet> (
				tv,
				source,
				(p) => p.IsPicked,
				(p, b) => p.IsPicked = b);

// Assign it to the TableView
tv.Table = withCheckboxes;
```

The index wrapper I think is still important/useful for when data is more traditional tabular data e.g. `System.Data.DataTable`.

**Comment by tznind** [comment]
> The only thing I noticed is `ListView` supports marking with single selection and uses the radio style mark for that.

Ok I will take a look at adding this feature, it shouldn't be too hard.

**Comment by tznind** [comment]
Radio buttons.  Enable by setting `UseRadioButtons`

radio-buttons

**Comment by tig** [comment]
@tznind: you have some merge conflicts here.

**Pull request merged**
