### PR TITLE
Fixes #2205. Reduce fragility of clipboard related unit tests

### LINKED ISSUE #2205: Reduce fragility of clipboard related unit tests
I am sure the fact that the unit tests regularly fail because the clipboard changes while they are running annoys you.

It annoys me.

I have a proposal, that I think will address this, and generally make the unit tests less fragile.

1) Ensure the only Unit Tests that actually talk to the real/underlying OS clipboard are those in `ClipboardTests.cs`. They should verify that Terminal.Gui's interaction with the OS clipboard on various platforms actually works.
2) Ensure that ALL other tests that verify the clipboard works (e.g. TextView's extensive cut/paste tests) use a FAKE `Clipboard` implementation.

Thoughts?

### PR DESCRIPTION
**Pull request by tig**
Fixes #2205

### CODE REVIEW

**Comment by tig** [comment]
Windows tests, before:
image

Windows tests, after:
image

So not significantly faster (was hoping that as a side benefit).

**Comment by tig** [comment]
@BDisp - Man, I feel your pain. The Clipboard on WSL and Linux is a mysterious beast!

I think I made solid progress in making the unit tests more robust with this PR. Please review.

@tznind, @BDisp (or anyone else) - please pull this down locally on a Mac AND *real* Linux install and test it please. I don't have either.

**Comment by tznind** [comment]
Can confirm that running Ubuntu laptop things work as expected.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

I was able to copy/paste when `xclip` was installed.  When it was not installed I was unable to copy and when I try to paste I get the text 'Clipboard Not Supported'.

**Comment by tznind** [comment]
I wonder if its worth having an event for clipboard read failure so users can handle it in an app specific way (e.g. show popup or revert to 'internal only clipboard')

**Comment by BDisp** [comment]
> @BDisp - Man, I feel your pain. The Clipboard on WSL and Linux is a mysterious beast!

I know :-) you learned the hard way that even you could install `xclip` in `WSL` it doesn't work at all and only `pwsh` works.

@tig this is broken on `WSL` on copy/paste:

imagem

**Comment by BDisp** [comment]
> I wonder if its worth having an event for clipboard read failure so users can handle it in an app specific way (e.g. show popup or revert to 'internal only clipboard')

I agree. In the `develop` branch if the clipboard isn't supported it fall to uses the internal clipboard. So the `Clipboard.Contents` is always set even the clipboard isn't supported.

**Comment by BDisp** [comment]
On `Mac` (on VirtualBox) all tests passes:

imagem

**Comment by tig** [comment]
> > I wonder if its worth having an event for clipboard read failure so users can handle it in an app specific way (e.g. show popup or revert to 'internal only clipboard')
> 
> I agree. In the `develop` branch if the clipboard isn't supported it fall to uses the internal clipboard. So the `Clipboard.Contents` is always set even the clipboard isn't supported.



> > I wonder if its worth having an event for clipboard read failure so users can handle it in an app specific way (e.g. show popup or revert to 'internal only clipboard')
> 
> I agree. In the `develop` branch if the clipboard isn't supported it fall to uses the internal clipboard. So the `Clipboard.Contents` is always set even the clipboard isn't supported.

To be clear, @tznind did you experience this not working, or are you speculating? I believe this is working properly (and have written additional unit tests to prove it). Thanks!

**Comment by tznind** [comment]
> To be clear, @tznind did you experience this not working, or are you speculating? I believe this is working properly (and have written additional unit tests to prove it). Thanks!

So when I clicked 'Paste' when xclip was not installed the text "Clipboard is not available" was pasted in.  This was a bit unexpected to me.  Its not bad behaviour but it doesn't help me as a user understand what I need to do to fix the clipboard.

As a developer it would be nice if it were easy to tailor the libraries behaviour under such circumstances e.g. instead of outputting "Clipboard not available" it could:

- Output nothing at all
- Copy/Paste from an internal 'memory only' clipboard class
- Display a modal dialog telling my users to install xclip (if on linux)

All three of these behaviours could be more user friendly depending on the target audience of the application being developed.

Its possible this is no longer the behaviour on this PR, I haven't re-tested it since my last post.

**Comment by tig** [comment]
Alright, I think I have everything fixed except the Curses reset issue @BDisp noted.

Still trying to figure that one out...

**Comment by tig** [comment]
> As a developer it would be nice if it were easy to tailor the libraries behaviour under such circumstances e.g. instead of outputting "Clipboard not available" it could:
> 
> * Output nothing at all
> * Copy/Paste from an internal 'memory only' clipboard class
> * Display a modal dialog telling my users to install xclip (if on linux)
> 

This is the correct behavior, IMO, and I just fixed a stupid mistake that makes it work this way (which is how it worked before):

> * Copy/Paste from an internal 'memory only' clipboard class

**Comment by BDisp** [comment]
> Alright, I think I have everything fixed except the Curses reset issue @BDisp noted.
> 
> Still trying to figure that one out...

One that is occur to me is any exception when is thrown deviates the execution of the reset.

**Comment by BDisp** [comment]
> Alright, I think I have everything fixed except the Curses reset issue @BDisp noted.
> 
> Still trying to figure that one out...

It seems to be fixed now. Perhaps some `Windows 11` update, don't know.

**Comment by tig** [comment]
Curses is still acting weird, but at least I got my VS2022/Windows Terminal config working again. The WT team got me a private build with a fix and I'm now unblocked.

**Comment by tig** [comment]
@BDisp - I cannot get breakpoints to hit when debugging in WSL on two different machines.

I have searched high and low and cannot find out what I'm doing wrong or have mis-configured. 

Do you have any suggestions on what I can try?

I can't finish this PR until I fix the bug I caused in the TextView/Editor scenario where copy/paste operations corrupt curses. And I can't figure out what's going on without being able to debug! 

Gracias for any help you can provide!

**Comment by tig** [comment]
Oh, and a clue to why VS WSL debugging isn't working is this, shown after I end a WSL debug session:

```
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[2440] wsl.exe' has exited with code 0 (0x0).
```

**Comment by BDisp** [comment]
The easiest way to debug `CursesDriver` in the `Visual Studio 2022` is run with `WSL2` selector and attach it to process. Place the breakpoints where you want and voila. 

imagem

imagem

**Comment by BDisp** [comment]
@tig this issue is already in the current develop branch. Will another PR caused this?

**Comment by tig** [comment]
@BDisp & @tznind if you struggle with this too, please upvote this 

https://developercommunity.visualstudio.com/myfeedback?port=1026&fsid=2f6ef04b-209f-4843-a386-43b80ca9c3c6

**Comment by tig** [comment]
> @tig this issue is already in the current develop branch. Will another PR caused this or some Windows update?

I see other oddities in `develop` when using the clipboard in the Editor scenario under WSL, but not screen corruption.

What, specifically, is the issue you see?

**Comment by BDisp** [comment]
> @BDisp & @tznind if you struggle with this too, please upvote this https://developercommunity.visualstudio.com/t/Debugging-dotnet-console-apps-in-VS2022/10242732?port=1025&fsid=11a4c115-97a0-4e4e-b986-b9a89b2838d7&ref=native&refTime=1672699586507&refUserId=5a90c5f2-d9f6-6a3a-8715-c058b3fda1aa

The correct link for others users is only https://developercommunity.visualstudio.com/t/Debugging-dotnet-console-apps-in-VS2022/10242732, otherwise we receive this warning:

imagem

**Comment by tig** [comment]
Based on the fact I can no longer reproduce the Editor issue where curses gets corrupted with this PR, I'm going to merge it. The benefits of all the work I did far outweigh an issue that is so hard to repo on WSL. 

If it repos again, we'll just open another issue for it.

**Pull request merged**
