### PR TITLE
Revamps CharMap

### PR DESCRIPTION
**Pull request by tig**
* Helps perf with a slight hack in `ScrollView` - contentView was clearing every draw!
* Better UI

@BDisp Can you please help me figure out why I'm losing my cursor, and why the down scrollbar button doesn't work, after the first mouse button click? I'm at my wits end. Thanks.

### CODE REVIEW

**Comment by BDisp** [comment]
> @BDisp Can you please help me figure out why I'm losing my cursor, and why the down scrollbar button doesn't work, after the first mouse button click? I'm at my wits end. Thanks.

I'll take a look at it.

@tig I added ordered list into the `CharMap` to help with the glyph. Do you want I submit a PR to your branch or can I commit within my PR #2620?

**Comment by tig** [comment]
> > @BDisp Can you please help me figure out why I'm losing my cursor, and why the down scrollbar button doesn't work, after the first mouse button click? I'm at my wits end. Thanks.
> 
> I'll take a look at it.
> 
> @tig I added ordered list into the `CharMap` to help with the glyph. Do you want I submit a PR to your branch or can I commit within my PR #2620?

I have tons of things I want to do to CharMap. Is the new list in this PR not ok? 

I plan on moving to a TableView for the range list with sortable columns and a filter... Feel free to do that ;-)

However, what I'd much rather you help with is to figure out how to build scrollbarview into View so ScrollView (with the insane ContentView) can be nuked from high-orbit with vengance (can you tell I'm frustrated with it ;-))?

**Comment by BDisp** [comment]
> I have tons of things I want to do to CharMap. Is the new list in this PR not ok?
> 
It's boring isn't ordered and jump on moving down from low to high and again to low all the times.

> I plan on moving to a TableView for the range list with sortable columns and a filter... Feel free to do that ;-)
> 
No, I prefer you do that. My change was only on a ordered range list, but since you intends to moving to a TableView (which is good) I'm not to submit my changes and wait for your CharMap revamps.

> However, what I'd much rather you help with is to figure out how to build scrollbarview into View so ScrollView (with the insane ContentView) can be nuked from high-orbit with vengance (can you tell I'm frustrated with it ;-))?

I'll do my best.

**Comment by tig** [comment]
> > @BDisp Can you please help me figure out why I'm losing my cursor, and why the down scrollbar button doesn't work, after the first mouse button click? I'm at my wits end. Thanks.
> 
> I'll take a look at it.
> 
> @tig I added ordered list into the `CharMap` to help with the glyph. Do you want I submit a PR to your branch or can I commit within my PR #2620?

Looks like the bottom-right thing fixed the scrollbar issue. However, I still can't figure out why I'm losing the cursor. To reproduce, scroll down by clicking in the middle of the scrollbar. You'll note you can't get the flashing cursor to reappear within the CharMap view unless you put the focus elsewhere and back again. What am I doing wrong?

**Comment by tig** [comment]
> > Looks like the bottom-right thing fixed the scrollbar issue. However, I still can't figure out why I'm losing the cursor. To reproduce, scroll down by clicking in the middle of the scrollbar. You'll note you can't get the flashing cursor to reappear within the CharMap view unless you put the focus elsewhere and back again. What am I doing wrong?
> 
> @tig the derived class `CharMap` must override the `PositionCursor` to handle the cursor position. See my commit in [339564d](https://github.com/gui-cs/Terminal.Gui/commit/339564d0f51c5aff11873443cac280d65689ff82)

I'm afraid you looked at an older version. The version in this PR *does* override `PositionCursor`. Can you look again, but at this code to see what I did incorectly?

**Comment by BDisp** [comment]
I don't like that the list view isn't sorted by the code point, which forces to jump into a disordered code points, see my changes in #2620. I can't typing anything int the jump to code point. What I'm typing is never what I see.

**Comment by tig** [comment]
@BDisp check it out now and lemme know what you think.

Next, I'd like to change the Jump To edit to be a filter that can filter either by range, category, or even glyph name.

Note that I added support to pull down glyph info from a web API (double click on a glyph) so we can get all the data.

**Comment by BDisp** [comment]
@tig this is much better. What impressive work. Now it's possible to sort by `Category` and `Start/End`. The interactive UI is spectacular. Thanks.

PS: I think it's better to keep a space column of 3 to allow having a spacing between two wider code points.

**Comment by BDisp** [comment]
When you finish this PR, I think it's better you merge this before #2620. After you done I'll merge the `v2_develop` with it and replace all the `CharMap` changes I've made with yours changes.

**Comment by tig** [comment]
> When you finish this PR, I think it's better you merge this before #2620. After you done I'll merge the `v2_develop` with it and replace all the `CharMap` changes I've made with yours changes.

But this PR is based on #2620. 

Also, not sure what you mean by:

> PS: I think it's better to keep a space column of 3 to allow having a spacing between two wider code points.

**Comment by tig** [comment]
> But this PR is based on #2620.

@BDisp I've brought your fixes from #2620 into this.

**Comment by BDisp** [comment]
> Also, not sure what you mean by:
> 
> > PS: I think it's better to keep a space column of 3 to allow having a spacing between two wider code points.

I mean this public` const int COLUMN_WIDTH = 2;` should be 3 instead of 2, otherwise wider runes may overlapped on both sides.

**Comment by BDisp** [comment]
> > But this PR is based on #2620.
> 
> @BDisp I've brought your fixes from #2620 into this.

Sorry @tig, my bad. Then if you feel well with your changes then merge again against the current #2620 and keep your changes and I'll close mine.

**Comment by tig** [comment]
> > Also, not sure what you mean by:
> > > PS: I think it's better to keep a space column of 3 to allow having a spacing between two wider code points.
> 
> I mean this public` const int COLUMN_WIDTH = 2;` should be 3 instead of 2, otherwise wider runes may overlapped on both sides.

I don't think so. Do you have an example? I can't find one that looks bad.

**Comment by BDisp** [comment]
> I don't think so. Do you have an example? I can't find one that looks bad.

I may be wrong but I think I already have seen some that were very leaning against each other. But never mind, if we discover some we fix later.

**Comment by tig** [comment]
> > I don't think so. Do you have an example? I can't find one that looks bad.
> 
> I may be wrong but I think I already have seen some that were very leaning against each other. But never mind, if we discover some we fix later.

I actually like it at 3! <3

**Pull request merged**
