### PR TITLE
Fixes #3273. Updates `FindDeepestView` to support `Adornment`

### LINKED ISSUE #3159: FrameToScreen/BoundsToScreen work, but are not correct
In #3158 I found the logic I put in these apis is not actually correct. It works with current Frame functionality but only by accident. 

This issue is to help me remember this needs to be fixed. 

The solve will be to make FrameToScreen recursive vs using a while loop. 

More unit tests are required in CoordinateTests.

### LINKED ISSUE #3273: Update `FindDeepestView` to support `Adornment`
- There are no dedicated unit tests for `FindDeepestView` right now. We need some. Write some that test the current `v2_develop` version that prove it works.

- The current version ignores `Adornments` and returns a view if x/y are anywhere within `view.Frame`. 

- Simplify `FindDeepestView` to NOT have the `out` params. 
  
- Modify `FindDeepestView` to return `Margin`, `Padding`, or `Border` if `x`/`y` match. In `Application.OnMouseEvent`, temporarily ignore these. Eg. like this:

```cs
        var view = View.FindDeepestView (Current, a.MouseEvent.X, a.MouseEvent.Y, out int screenX, out int screenY);

        // TODO: Remove this temporary filter:
        if (view is Adornment adornment)
        {
            view = adornment.Parent;
        }
```

- Add `FindDeepestView` unit tests to prove this change works.

- Delete all the `Adornment`-specific code in `Application.OnMouseEvent` and add `MouseEvent` handling code to `Adornment`, `Margin`, `Border`, and `Padding` as appropriate (e.g. `Adornment.MouseClick += Parent.SetFocus()`).

- Don't worry about `Adornment.SubViews` yet. That should happen in either THIS PR or the `Close Box` PR.

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- Fixes #3273 
- Fixes #3159 

Is dependent on 

- #3281 

See also:

- #2994 

## Proposed Changes/Todos

- [x] Modify `FindDeepestView` to return `Margin`, `Padding`, or `Border` if `x`/`y` match. 
- [x] Add `MouseEvent` handling code to `Adornment`, `Margin`, `Border`, and `Padding` as appropriate (e.g. `Adornment.MouseClick += Parent.SetFocus()`).
- [x] Add more `FindDeepestView` unit tests to prove this change works.
- [x] Move drag support out of `Toplevel` into `Adornment` - Dragging margin or border drags the view.
- [x] Drag support is not quite right - dragging anywhere on border.Thickness SHOULD work, but only top does
- [x] Add support for `Adornment.SubViews`
- [ ] Computed Layout for  `Adornment.SubViews` is not working right always.

  e.g. `var btnButtonInPadding = new Button { X = Pos.Center (), Y = Pos.Center (), Text = "_Button in Padding" };` in `Adornments` scenario doesn't work (the Y =).

- [ ] Figure out best place for adornments to add their own subviews. Can't do it in constructor or `Initialized` event. 
- [ ] Add a prototype Close button to Border - partially implemented.
- [ ] Focus on a  `Adornment.SubView` is not working.
- [ ] When a subview of an `Adornment` gets focus, `Adornment.Parent` should get focus.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
@BDisp please check this out.

Adornment now handles `Toplevel` drag. Eventually, when 

- #2537 

is completed, any View will support move/sizing. For now, I've hacked in at test for `Parent is not Toplevel`.

**Review by dodexahedron — COMMENTED** [review]
🙂

**Comment by BDisp** [comment]
I need the missing the out parameters. Now I can't have the subviews on adornmemts working anymore. I hope you fix that before the dragging feature.

**Comment by tig** [comment]
> I need the missing the out parameters. Now I can't have the subviews on adornmemts working anymore. I hope you fix that before the dragging feature.

I don't recall what you mean by "the out parameters."  Please remind me.

**Comment by BDisp** [comment]
> I don't recall what you mean by "the out parameters." Please remind me.

Surely. When you refactored `FindDeepestView` to support adornments, you got rid of the output parameters, `rx` and `ry`. I used these values returned by the adornment to recall `FindDeepestView` and get the adornment's subview. Without these output parameters I am no longer able to do this.
Imagine you have a subview inside a superview that contains border. The subview has the Frame.Location as (0,0) and Padding.Thickness as (0,0,1,0). Padding has a subview like (0,0,Dim.Fill(),Dim.Fill). If the mouse is at position (0,0) of the Padding subview, `FindDeepestView` returns the correct padding, but when I call FindDeepestView again to return its subview it returns null because I'm not calling it with the correct location that was previously obtained with the return of the output parameters. `FrameToScreen` returns (1,1) or (1,2) if there is a `MenuBar` and it becomes more difficult to get the values to be sent to return the correct subview.

**Comment by tig** [comment]
> > I don't recall what you mean by "the out parameters." Please remind me.
> 
> Surely. When you refactored `FindDeepestView` to support adornments, you got rid of the output parameters, `rx` and `ry`. I used these values returned by the adornment to recall `FindDeepestView` and get the adornment's subview. Without these output parameters I am no longer able to do this. Imagine you have a subview inside a superview that contains border. The subview has the Frame.Location as (0,0) and Padding.Thickness as (0,0,1,0). Padding has a subview like (0,0,Dim.Fill(),Dim.Fill). If the mouse is at position (0,0) of the Padding subview, `FindDeepestView` returns the correct padding, but when I call FindDeepestView again to return its subview it returns null because I'm not calling it with the correct location that was previously obtained with the return of the output parameters. `FrameToScreen` returns (1,1) or (1,2) if there is a `MenuBar` and it becomes more difficult to get the values to be sent to return the correct subview.

Right.

What you're needing, and what I'll get you asap, is for `FindDeepestView` to recurse in to `padding.SubViews` here:

https://github.com/gui-cs/Terminal.Gui/blob/3a834ac5dce67ec420458248732970d5b37e9ee7/Terminal.Gui/View/Layout/ViewLayout.cs#L602

**Comment by BDisp** [comment]
> Right.
> 
> What you're needing, and what I'll get you asap, is for `FindDeepestView` to recurse in to `padding.SubViews` here:
> 
> https://github.com/gui-cs/Terminal.Gui/blob/3a834ac5dce67ec420458248732970d5b37e9ee7/Terminal.Gui/View/Layout/ViewLayout.cs#L602

Yes I know. I already I'm using it but but with no success for now. Thanks.

**Comment by BDisp** [comment]
> What did you try?
> 
> Have you merged this PR into yours?
> 

No, I just trying to merge the v2_develop branch into my PR #3254 and using some code you are using on this PR but I cannot make it work as before, because I can't send the right coordinates to the Padding's subview on the MouseEvent.

> Or, are you just trying an experiment on a fork of this PR?

No, because none of yours WIP PR or the already merged one handles subviews into adornments. It's working fine to deal with adornments but not with subviews in adornments.

**Comment by tig** [comment]
> > What did you try?
> > Have you merged this PR into yours?
> 
> No, I just trying to merge the v2_develop branch into my PR #3254 and using some code you are using on this PR but I cannot make it work as before, because I can't send the right coordinates to the Padding's subview on the MouseEvent.
> 
> > Or, are you just trying an experiment on a fork of this PR?
> 
> No, because none of yours WIP PR or the already merged one handles subviews into adornments. It's working fine to deal with adornments but not with subviews in adornments.

Just to bubble up what's going on so we're on the same page:

- When I first did the `Frame/Adornment` work, I knew it was not done. I knew there were likely bugs and stuff i had not considered, particularly relating to mouse input. 
  - I created this issue to try to track all of these: https://github.com/gui-cs/Terminal.Gui/issues/2994
- Before you started on #3254, `v2_develop` had multiple egregious bugs in it relative to `Adoornment` coordinates. 
- I fixed SOME of these in https://github.com/gui-cs/Terminal.Gui/pull/3277.
- I started this PR in order to fix more of them, particularly issues around `FindDeepestView`. 
  - Step one was for me to get a deeper understanding of how `Application.OnMouseEvent` and `View.OnMouseEvent` worked (or should work). This resulted in me fixing more issues in https://github.com/gui-cs/Terminal.Gui/pull/3281
  - Step two was to ensure I could really make `FindDeepestView` work for enabling `Adornment` to get proper mouse events; to do this I decided to make progress on https://github.com/gui-cs/Terminal.Gui/issues/2491, by moving the drag-to-move code into `Adornment`. I'm ALMOST done with this.
  - Step three is to ensure `FindDeepestView` recurses into the `Adornments.SubViews` so that subviews of `Adornments` "just work".

**Comment by tig** [comment]
Fuck. I screwed something up trying to rebase. Arrrrrggg!!!

**Comment by tig** [comment]
@BDisp / @dodexahedron 

If either of you pulled this branch down yesterday afternoon PLEASE DON'T DELETE IT.

I somehow completely clobbered this PR trying rebase and everything I did yesterday is GONE.

I have an older version at home, but it's missing everythign I did yesterday!

**Comment by BDisp** [comment]
Sorry @tig I didn't pull it. See if you have some stash you can recover from.

**Comment by tig** [comment]
Fuck. My branch on my home computer was last updated 3/1. That's 4 fraking days of REALLY GREAT (if I say so myself) work, GONE.

**Comment by tig** [comment]
I think I found it!!!

https://github.com/gui-cs/Terminal.Gui/tree/98eba9a9039f8477ed9dd2392d702e49de8538af

**Comment by tig** [comment]
Back! Yay.

https://github.com/gui-cs/Terminal.Gui/pull/3295

**Comment by dodexahedron** [comment]
Yay.

Yeah, your remote will always have whatever you last pushed to it until you force push over it. Handy in case you do something unfortunate or even if you simply want to try doing it another way, like maybe squashing or re-ordering a few commits.

Another option, however, that is much safer, is that, instead of force pushing over the original branch, change the remote branch name and push to an entirely new branch. That won't be a force push and you can then hold on to your old branch until you feel safe to just delete it altogether.

I generally don't pull anything from non-origin forks except explicitly to test or debug something. Although doing so is _less_ dirty now than it was before fixing the merge strategy. When I do, though, I clone my working copy to a dedicated folder. While that's not really necessary, it is easier (read: lazier 😅) than pulling the remote fork branch to my repo and ensuring everything is properly committed/stashed/etc before that.

I also will sometimes copy my local repo if I'm about to do something I'm either unsure of or that risks losing work, so that rolling back the operation is as simple as deleting the working copy and copying the backup copy back to the original location. Then I don't have to think so much about how to undo something or what commit is proper to reset to or what _kind_ of reset is correct, or _whatever._

**Pull request closed without merging**
