### PR TITLE
Added check for hidden columns

### PR DESCRIPTION
**Pull request by Phyyl**
Adds support for MappingType.Hidden to hide columns in TableView

### CODE REVIEW

**Comment by tznind** [comment]
Thanks for opening this PR.  There is an issue https://github.com/migueldeicaza/gui.cs/issues/1465 in which some of the complexity of hidden columns is discussed. 

Please can you add a unit test to TableViewTests that shows how the new code works and a setting in [TableEditor](https://github.com/migueldeicaza/gui.cs/blob/main/UICatalog/Scenarios/TableEditor.cs) for hidding a column(s) so that the feature can be tested both in CI and in user interaction?

**Review by tig — CHANGES_REQUESTED** [review]
Per @tznind : Please can you add a unit test to TableViewTests that shows how the new code works and a setting in [TableEditor](https://github.com/migueldeicaza/gui.cs/blob/main/UICatalog/Scenarios/TableEditor.cs) for hidding a column(s) so that the feature can be tested both in CI and in user interaction?

**Review by tig — APPROVED** [review]
LGTM. Im going to merge this now because I want to get the updated release out today. Please do a another PR with the requested tests asap. Thanks!

**Comment by tig** [comment]
Actually, scratch that. There are now merge conflicts.

Can you please fix?

I'm going to release 1.6.4 without this.

**Comment by Phyyl** [comment]
Yes, I'll make the changes, it can be in an other release, we use it as a submodule so we're not in a hurry for the feature to be released. I can't right now but by tomorrow I'll have it done

**Comment by tig** [comment]
@Phyyl, you still working on this?

**Comment by Phyyl** [comment]
@tig sorry life got in the way. I;m confortable closing this for the time being unitl I can work on it later, or letting someone else pick back up the task. I hadn't thought about the impact this would have and I unfortunately don't have the time these days.

**Pull request closed without merging**
