### PR TITLE
Fixes #2249. CharacterMap isn't refreshing well non-BMP code points on scroll.

### LINKED ISSUE #2249: CharacterMap isn't refreshing well non-BMP code points on scroll.
It's showing this:

imagem

But must showing this:

imagem

### PR DESCRIPTION
**Pull request by BDisp**
Fixes #2249 - Also improves the searching glyph by selecting and make visible the related value found in the `ListView`.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
Also fixes this;

imagem

imagem

**Comment by BDisp** [comment]
With `WindowsDriver` and with windows console host I can achieve this:

imagem

But with `Windows Terminal` it's all mess up:

imagem

**Review by tig — APPROVED** [review]
Nice work.

**Comment by tig** [comment]
> With `WindowsDriver` and with windows console host I can achieve this:
> 
> imagem
> 
> But with `Windows Terminal` it's all mess up:
> 
> imagem

Is there an Issue filed against Windows Terminal on this?

**Comment by BDisp** [comment]
> Is there an Issue filed against Windows Terminal on this?

I don't think there is. I think you may ask them. I don't know if I'm doing something wrong.

**Comment by tig** [comment]
> > Is there an Issue filed against Windows Terminal on this?
> 
> I don't think there is. I think you may ask them. I don't know if I'm doing something wrong.

They are quite responsive. I suggest you file an Issue

https://github.com/microsoft/terminal/issues

**Comment by DHowett** [comment]
FWIW, `U+1D53D MATHEMATICAL DOUBLE-STRUCK CAPITAL F` and friends are all indicated in the Unicode character database as occupying one column (`ea=N Emoji=N EPres=N`).

If I had to guess, it's actually a bug that they're being displayed in _two_ columns in the old Windows console host! 🙂 

(Terminal has broadly better Unicode compatibility than the Console does, because it has a faster release cycle and we've been able to fix it much more quickly.)

**Comment by BDisp** [comment]
Thanks for your answers @DHowett. The problem is if I consider it as one column it also appear misaligned. Where can I get the information about how many columns a code point occupies?

**Comment by tig** [comment]
@BDisp -should this be marked as a draft PR?

**Comment by tig** [comment]
@BDisp I pulled this down locally. I noted this. I'm not sure if this is the same issue you are attempting to fix with this PR, but I thought I'd let you know:

SkqFtdL 1

**Comment by BDisp** [comment]
> @BDisp I pulled this down locally. I noted this. I'm not sure if this is the same issue you are attempting to fix with this PR, but I thought I'd let you know:

Yes it's. Non-BMP cannot be used with the current `WindowsDriver` because it only allow handle it by using two blocks or columns and not all them occupies two columns. I'm working on changing the write API to another type which can handle 32 bits characters.

**Comment by tig** [comment]
> > @BDisp I pulled this down locally. I noted this. I'm not sure if this is the same issue you are attempting to fix with this PR, but I thought I'd let you know:
> 
> Yes it's. Non-BMP cannot be used with the current `WindowsDriver` because it only allow handle it by using two blocks or columns and not all them occupies two columns. I'm working on changing the write API to another type which can handle 32 bits characters.

Got it.

Do you have an ETA for the fix? I'm asking because we need to get a release out. I'm thinking that if you need more time, then I'll do a PR for CharMap that disables those ranges for now. What do you think?

**Comment by BDisp** [comment]
> Do you have an ETA for the fix? I'm asking because we need to get a release out. I'm thinking that if you need more time, then I'll do a PR for CharMap that disables those ranges for now. What do you think?

No, sorry I don't have an ETA for the fix, so is better you do a PR for disable those ranges for now. Thanks.

**Comment by BDisp** [comment]
@tig the fixes included in this PR for `Toplevel` and `ListView` are in #2267 and #2270, so we can leverage them for the new package while the non-BMP fixes aren't ready for the others drivers.

**Pull request closed without merging**
