### PR TITLE
Fixes #2201. Update CsvEditor scenario to use CsvHelper

### LINKED ISSUE #2201: CsvEditor: If decimal separator is comma it throws an an exception on open.
If decimal separator is the comma it throw an an exception on open. I think there must a flag to allow comma as decimal separator if it's in quotes "12,05".

imagem

_Originally posted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/2195#issuecomment-1305859000_

### PR DESCRIPTION
**Pull request by tznind**
Fixes #2201- Update CsvEditor example scenario in UICatalog to use CsvHelper instead of bespoke weak parsing code.

The new dependency is CsvHelper (https://github.com/JoshClose/CsvHelper).  It has ~112M downloads.  The dependency only affects the UICatalog and not the main Terminal.Gui project.  

I looked at [TinyCsvParser](https://github.com/TinyCsvParser/TinyCsvParser) but it doesn't seem easy to use for tabular data (its more of an Object Relational Mapper).

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
@BDisp let me know if you have a CSV that loads in Excel/Libre Office (or similar) but not in this new version.

**Comment by BDisp** [comment]
> @BDisp let me know if you have a CSV that loads in Excel/Libre Office (or similar) but not in this new version.

Here it's [Friends3.csv](https://github.com/gui-cs/Terminal.Gui/files/9955089/Friends3.csv) modified. Don't forget only open it after open the Excel and not by double click, to been open a dialog where you can configure the delimiter, if it has header and in the advanced chose the comma as decimal separator.

**Comment by BDisp** [comment]
Friends.csv doesn't format as datatable:

imagem

Friends3.csv:

imagem

**Comment by tznind** [comment]
That's weird, it opens fine on mine:

working

**Comment by BDisp** [comment]
> That's weird, it opens fine on mine:

I know, you have to check the client culture to process the necessary config.

**Comment by tznind** [comment]
Hmn... Can you try changing `CultureInfo.CurrentCulture` to `Invariant` in this PR and tell me if that fixes it for you?

I don't really understand how culture affects CSV escaping.  Usually its only datatype parsing.  Are you sure the file that doesn't open correctly is 100% the same as the one you linked me above?

**Comment by BDisp** [comment]
Another suggestion is allowing a configurable dialog option to choice other settings.

**Comment by BDisp** [comment]
> Hmn... Can you try changing `CultureInfo.CurrentCulture` to `Invariant` in this PR and tell me if that fixes it for you?

Yes it fix it, thanks. Add to the Setup first line please. Thanks.

**Comment by tznind** [comment]
> > Hmn... Can you try changing `CultureInfo.CurrentCulture` to `Invariant` in this PR and tell me if that fixes it for you?
> 
> Yes it fix it, thanks. Add to the Setup first line please. Thanks.

Cool glad it is fixed although not sure I fully understand why!  It is now `CultureInfo.InvariantCulture`.

Is that what you meant by "Add to the Setup first line please"?

**Comment by BDisp** [comment]
> I don't really understand how culture affects CSV escaping. Usually its only datatype parsing. Are you sure the file that doesn't open correctly is 100% the same as the one you linked me above?

Yes it affect because depends on the culture, the delimiters (comma, semicolon, space, tab, others), fixed width, headers, decimal separator, thousands separator, etc.

**Comment by BDisp** [comment]
> > > Hmn... Can you try changing `CultureInfo.CurrentCulture` to `Invariant` in this PR and tell me if that fixes it for you?
> > 
> > 
> > Yes it fix it, thanks. Add to the Setup first line please. Thanks.
> 
> Cool glad it is fixed although not sure I fully understand why! It is now `CultureInfo.InvariantCulture`.
> 
> Is that what you meant by "Add to the Setup first line please"?

Yes.
```cs
public override void Setup ()
		{
			CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;

			Win.Title = this.GetName();
			Win.Y = 1; // menu
			Win.Height = Dim.Fill (1); // status bar
			Application.Top.LayoutSubviews ()
```;

**Comment by tznind** [comment]
Ah ok I understand now.  I actually just changed it in the reader/writer code: https://github.com/gui-cs/Terminal.Gui/pull/2202/commits/a0686dfcde3bd20fceaac8f01f91fa372bb44493

Can you confirm that this has same effect for you.

I didn't know that `CultureInfo` affected default separator for CSV that seems very strange to me.

**Comment by BDisp** [comment]
> Its a more limited change and won't affect other stuff in app. Can you confirm that this has same effect for you.

It working well too. Thanks.

**Comment by tznind** [comment]
Thanks for taking the time to check

**Comment by BDisp** [comment]
@tznind can I suggest you can merge the open file name with the window title, please. Like `Csv Editor - Friends.csv`.

**Review by tig — APPROVED** [review]

**Comment by tig** [comment]
@tznind please fix merge conflicts and I'll merge.

**Comment by tznind** [comment]
Thanks, have fixed the merge conflicts

**Pull request merged**
