### PR TITLE
Fixes #3109. AOT support with .Net 8.

### LINKED ISSUE #3109: AOT support with .Net 8?
## Required reading:

- https://sentry.engineering/blog/should-you-could-you-aot

## ToDos:

- [ ] Annotate anywhere reflection is used.
- [ ] Figure out how to refactor `ConfigurationManager` given it is heavy on reflection AND serialization

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3109

## Proposed Changes/Todos

- [x] Add a native AOT project.
- [x] Adapt Text.Json to work properly.
- [x] Add in AutoInitShutdownAttribute attribute the possibility to have a different configuration in the config.json and with the unit tests. This avoid to force the config.json having the same configuration as the unit test.
- [x] Fix bug with the color formatting which throw an exception for the Red color.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — APPROVED** [review]
LGTM. I may have broken something with my fixing of merge conflicts though!

**Comment by BDisp** [comment]
Considerations to take an account when working with `Text.Json` and `native AOT`:

- When creating new enum types or an already existed one, that are used on properties using CM, this statements are mandatory:

```cs
using System.Text.Json.Serialization;

namespace Terminal.Gui;

[JsonConverter (typeof (JsonStringEnumConverter<MyEnum>))]
public enum MyEnum
{}
```
- Add them into `SourceGenerationContext` class:

```cs
...
[JsonSerializable (typeof (MyEnum))]
```
- In all properties that uses these enum types in the CM, this statements are mandatory:

```cs
[SerializableConfigurationProperty (Scope = typeof (MyScope))]
public static MyEnum DefaultMyEnum { get; set; } = MyEnum.{Wathever}; // Default is set in config.json
```
- Without theses procedures the executable native AOT file, will silently throwing exceptions and showing a default white/black and with all empty configurations.

**Comment by tig** [comment]
> Considerations to take an account when working with `Text.Json` and `native AOT`:
> 
> * When creating new enum types or an already existed one, that are used on properties using CM, this statements are mandatory:
> 
> ```cs
> using System.Text.Json.Serialization;
> 
> namespace Terminal.Gui;
> 
> [JsonConverter (typeof (JsonStringEnumConverter<MyEnum>))]
> public enum MyEnum
> {}
> ```
> 
> * Add them into `SourceGenerationContext` class:
> 
> ```cs
> ...
> [JsonSerializable (typeof (MyEnum))]
> ```
> 
> * In all properties that uses these enum types in the CM, this statements are mandatory:
> 
> ```cs
> [SerializableConfigurationProperty (Scope = typeof (MyScope))]
> public static MyEnum DefaultMyEnum { get; set; } = MyEnum.{Wathever}; // Default is set in config.json
> ```
> 
> * Without theses procedures the executable native AOT file, will silently throwing exceptions and showing a default white/black and with all empty configurations.

Could you add a unit test that verifies all these conditions are true for any enum defined in the libarary?

**Comment by BDisp** [comment]
> Could you add a unit test that verifies all these conditions are true for any enum defined in the libarary?

If you know how to can run unit tests from a executable, of course. The problem is that the unit tests are tested with al the library on the `bin/Debug/net8.0` folder and the published executable is a trimmed file with the necessary library embedded. I only can test it when I run the executable file.

**Comment by tig** [comment]
> > Could you add a unit test that verifies all these conditions are true for any enum defined in the libarary?
> 
> If you know how to can run unit tests from a executable, of course. The problem is that the unit tests are tested with al the library on the `bin/Debug/net8.0` folder, where no exception is throwed and the published executable is a trimmed file with the necessary library embedded. I only can test it when I run the executable file.

I must not have made myself clear:

- You put forth a bunch of "rules above". Those rules require attributing enums with stuff.
- It is possible to use reflection to examine every enum in `Terminal.Gui` to see if they have those attributes

It should be possible to build a unit test that verifies that any newly added enums have those attributes.

**Comment by BDisp** [comment]
> I must not have made myself clear:
> 
> * You put forth a bunch of "rules above". Those rules require attributing enums with stuff.
> * It is possible to use reflection to examine every enum in `Terminal.Gui` to see if they have those attributes
> 

But these attributes are only needed to be added if they are used on `Text.Json.Serialization`. Enums that aren't used on `Text.Json.Serialization` don't need to be added.

> It should be possible to build a unit test that verifies that any newly added enums have those attributes.

Only if they are used on `Text.Json.Serialization`.  But if they are added to the both places, JsonSerializerContext and on each property which use them,  also throws silently an exception when a  published executable `native AOT` file runs.
 I really haven't idea how to do that. Can you help?

**Comment by BDisp** [comment]
@tig I changed the `NativeAot` project to `ThrowOnJsonErrors`. Try to add `[JsonConverter (typeof (JsonStringEnumConverter<Alignment>))]` to the `Dialog.DefaultButtonAlignment`, publish and run it from a command line. You'll see the app crashing with an exception. I think this way is better than providing a with/black window with empty configuration.

**Comment by tig** [comment]
> @tig I changed the `NativeAot` project to `ThrowOnJsonErrors`. Try to add `[JsonConverter (typeof (JsonStringEnumConverter<Alignment>))]` to the `Dialog.DefaultButtonAlignment`, publish and run it from a command line. You'll see the app crashing with an exception. I think this way is better than providing a with/black window with empty configuration. 

So you think it's better to let a developer have to get all the way to publishing the NaviteAot project to discover they missed following instructions than having a test in `./UnitTests` that makes it clear as soon as they intoduce an enum and try to test?

**Comment by BDisp** [comment]
> So you think it's better to let a developer have to get all the way to publishing the NaviteAot project to discover they missed following instructions than having a test in `./UnitTests` that makes it clear as soon as they intoduce an enum and try to test?

The user doesn't have to worry about that. Must be us, as maintainer ensuring the `NativeAot` runs without throwing an exception and that was what I did by fixing the necessary to the project running without any issue. Thus, on every new package we need to publish the `NativeAot` to check if it run successfully, ensuring that any developer that want to use a native AOT project runs without any issues related with `Terminal.Gui`. I understand that an unit test will be great but it's not very easy as you think. You need to use compile code generation, publish and check for any throwed exception. But that stuff isn't very easy to do for a newbie :-)

**Comment by tig** [comment]
> > So you think it's better to let a developer have to get all the way to publishing the NaviteAot project to discover they missed following instructions than having a test in `./UnitTests` that makes it clear as soon as they intoduce an enum and try to test?
> 
> The user doesn't have to worry about that. Must be us, as maintainer ensuring the `NativeAot` runs without throwing any exception and that was what I did by fixing the necessary to the project running without any issue. Thus, on every new package we need to publish the `NativeAot` to check if it run successfully, ensuring that any developer that want to use a native AOT project runs without any issues related with `Terminal.Gui`. I understand that an unit test will be great but it's not very easy as you think. You need to use compile code generation, publish and check for any throwed exception. But that stuff isn't very easy to do for a newbie :-)

First, we have a bunch of unit tests that are for US. E.g. all the Disposed stuff. It has saved countless hours of OUR time.

Second, I don't think it's that hard to make a unit test that does what I suggest. No, I'm not going to do it just to prove it. 

I guarantee, though, that at some point in the future one of us maintainers is going to forget to properly attribute an enum and the only way we'll find out is because someone ELSE tries to publish a Native AOT app. When that happens that will be OUR fault, for not taking the time to build as much testing in as we can.

**Comment by BDisp** [comment]
Well you can try to do yourself because it's beyond of my limits.

**Comment by tig** [comment]
> Well you can try to do yourself because it's beyond of my limits.

I'm sorry you feel that way.  It would be great if you would reconsider.

**Comment by tig** [comment]
image

**Comment by BDisp** [comment]
I don't have Copilot but I'll try do it.

**Comment by tig** [comment]
I could have asked ChatGPT or any other of a dozen free dev AIs.

**Comment by BDisp** [comment]
Done @tig.

### Explanation:
**1. Assembly and Types Inspection:**

- The assembly variable retrieves the assembly containing the `SourceGenerationContext` class.
- The code loops through all types in this assembly to gather properties decorated with the `SerializableConfigurationProperty` attribute.

**2. Collecting Property Types:**

- The test collects distinct property types that are decorated with `SerializableConfigurationProperty`.

**3. Get Registered Types:**

- The `GetRegisteredTypes` method uses reflection to inspect the `JsonSerializerContext` derived class and find all types registered for serialization.
- It looks for properties of type `JsonTypeInfo<T>` to determine the registered types.

**4. Assertions for Properties:**

- Ensure each property type is included in the registered types.
- Verify that no properties have the generic `JsonStringEnumConverter<>` attribute.

**5. Identifying Classes with `ScopeJsonConverter<>`:**

- The test finds all classes in the assembly that are decorated with the `[JsonConverter(typeof(ScopeJsonConverter<>))]` attribute.
- It checks to ensure these classes are also registered in the `JsonSerializerContext`.

This comprehensive approach ensures that all relevant types are checked and validated, maintaining the robustness and flexibility of the test.

**Comment by tig** [comment]
Ready to merge?

**Comment by BDisp** [comment]
> Ready to merge?

Yes. Thanks.

**Comment by BDisp** [comment]
@tig I don't know if the test will not fail it another derived from type of `JsonConverterAttribute` than `typeof (ScopeJsonConverter<>)` that you can use in the future. Do you want I prevent that situations in this PR?

**Comment by tig** [comment]
> @tig I don't know if the test will not fail it another derived from type of `JsonConverterAttribute` than `typeof (ScopeJsonConverter<>)` that you can use in the future. Do you want I prevent that situations in this PR?

Nah. That seems rare enough that we're probably ok until it becomes a problem.

**Comment by BDisp** [comment]
Sorry @tig al least I learn that is impossible to test from all JsonConverter<> derived classes because we need the types passed in the generic at runtime and not at compile time. So, DictionaryJsonConverter<T> the T type will be only know at run time.
Ready for review, thanks.

**Pull request merged**
