### PR TITLE
Fixes #1959. GoToEnd should not fail on an empty TreeView

### LINKED ISSUE #1959: GoToEnd should not fail on an empty TreeView
**Describe the bug**
When the `End` key is pressed on an empty TreeView, an exception is thrown.

Exception:
System.InvalidOperationException: 'Sequence contains no elements'

**To Reproduce**
1. Run the UICatalog project.
2. Click on the `TreeView` category
3. Double click on Interactive Tree
4. Press the `End` key on your keyboard
5. An `InvalidOperationException` is thrown with the message `Sequence contains no elements`

**Expected behavior**
When the `End` key is pressed on an empty TreeView, no exception should be thrown.

### PR DESCRIPTION
**Pull request by jmelosegui**
Fixes #1959  - GoToEnd should not fail on an empty TreeView

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by BDisp — APPROVED** [review]

**Review by BDisp — APPROVED** [review]

**Review by tig — COMMENTED** [review]
Thank you!

**Review by tig — APPROVED** [review]

**Review by tig — APPROVED** [review]
Nicely done. Thank you!

**Comment by jmelosegui** [comment]
@tig thanks for merging this PR.
Question.
What is the frequency in which the master branch is updated and a new nuget version is published to nuget.org?

**Comment by tig** [comment]
When someone asks me to do it ;-)

**Pull request merged**
