### PR TITLE
Fixes #1720 - `ColorPicker` pop up example (in `ProgressBarStyles` Scenario)

### LINKED ISSUE #1720: Add ColorPicker pop-up example
Very related to 

- #2800

I already coded this up as part of my code review of `ColorPicker` (#1668). But I didn't add it because I built it on `ProgressBar Styles` and it really should be part of the `Color Picker` Scenario.

This code shows how to wrap `Color Picker` in a `Dialog` such that when you click on a color, the dialog closes and the `ProgressBar` colors change. 

My suggestion is to add a `ProgressBar` to the `Color Picker` scenario and use this code (or an adaptation) to make it sing:

```csharp
		#region ColorPicker
		ColorName ChooseColor (string text, ColorName colorName)
		{

			var colorPicker = new ColorPicker {
				Title = text,
				SelectedColor = colorName
			};

			var dialog = new Dialog {
				Title = text
			};

			dialog.LayoutComplete += (sender, args) => {
				// TODO: Replace with Dim.Auto
				dialog.X = pbList.Frame.X;
				dialog.Y = pbList.Frame.Height;

				// Once #3127 is merged:
				dialog.LayoutStyle = LayoutStyle.Absolute;
				dialog.Bounds = new Rect (0, 0, colorPicker.Frame.Width, colorPicker.Frame.Height);

				Application.Top.LayoutSubviews ();
			};

			dialog.Add (colorPicker);
			colorPicker.ColorChanged += (s, e) => {
				dialog.RequestStop ();
			};
			Application.Run (dialog);

			var retColor = colorPicker.SelectedColor;
			colorPicker.Dispose ();

			return retColor;
		}

		var fgColorPickerBtn = new Button {
			Text = "Foreground HotNormal Color",
			X = Pos.Center (),
			Y = Pos.Bottom (pbList),
		};
		editor.Add (fgColorPickerBtn);
		fgColorPickerBtn.Clicked += (s, e) => {
			var newColor = ChooseColor (fgColorPickerBtn.Text, editor.ViewToEdit.ColorScheme.HotNormal.Foreground.ColorName);
			var cs = new ColorScheme (editor.ViewToEdit.ColorScheme) {
				HotNormal = new Attribute (newColor, editor.ViewToEdit.ColorScheme.HotNormal.Background)
			};
			editor.ViewToEdit.ColorScheme = cs;
		};

		var bgColorPickerBtn = new Button {
			X = Pos.Center (),
			Y = Pos.Bottom (fgColorPickerBtn),
			Text = "Background HotNormal Color"
		};
		editor.Add (bgColorPickerBtn);
		bgColorPickerBtn.Clicked += (s, e) => {
			var newColor = ChooseColor (fgColorPickerBtn.Text, editor.ViewToEdit.ColorScheme.HotNormal.Background.ColorName);
			var cs = new ColorScheme (editor.ViewToEdit.ColorScheme) {
				HotNormal = new Attribute (editor.ViewToEdit.ColorScheme.HotNormal.Foreground, newColor)
			};
			editor.ViewToEdit.ColorScheme = cs;
		};
```

image

Tag @jocelynnatali

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- Fixes #1720

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
How about popup near the respective buttons on available space (below, up, right, left) as the `ContextMenu` does?

**Comment by tig** [comment]
> How about popup near the respective buttons on available space (below, up, right, left) as the `ContextMenu` does?

Yea, that's a bug. I'll fix.

**Comment by tig** [comment]
https://github.com/gui-cs/Terminal.Gui/assets/585482/d827ae17-6f8a-4d22-8f87-9b93c9469e3a

**Comment by BDisp** [comment]
@tig in my opinion if you click on the Foreground button the popup should appear bellow the bottom of the button. See the case of the `ContextMenu`:

image

**Comment by tig** [comment]
> @tig in my opinion if you click on the Foreground button the popup should appear bellow the bottom of the button. See the case of the `ContextMenu`:

100% agree.

I am not going to spend the time now implementing this in `ProgressBarStyles.cs`.

Instead, it should be a built-in feature as part of 

- #2491

**Comment by BDisp** [comment]
> 100% agree.
> 
> I am not going to spend the time now implementing this in `ProgressBarStyles.cs`.
> 
> Instead, it should be a built-in feature as part of

Of course that this have more sense for a built-in generic popup that can be popup by any view and with any view content inside the popup.

**Pull request merged**
