### PR TITLE
Simplify MakePrintable by using AND and avoiding converting to string

### PR DESCRIPTION
**Pull request by pavkam**
This PR simplifies MakePrintable by using simpler bitwise OR instead of string manipulation.

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Review by tig — CHANGES_REQUESTED** [review]
Can you please provide a unit test that helps ensure this won't cause a regression? 

I really appreciate your attention to detail and am excited to have you helping!

**Comment by pavkam** [comment]
@tig -- added two parameterized tests

**Review by tig — CHANGES_REQUESTED** [review]
Before I accept this, I'd like confirmation that this change has been thoroughly tested on Windows, Linux, and the Mac. 

I don't fully understand the code paths/scenarios involved where this method is used and am nervous about introducing a regression in an area where we have really poor unit testing (all drivers).

**Review by BDisp — APPROVED** [review]

**Comment by pavkam** [comment]
> Before I accept this, I'd like confirmation that this change has been thoroughly tested on Windows, Linux, and the Mac. 
> 
> 
> 
> I don't fully understand the code paths/scenarios involved where this method is used and am nervous about introducing a regression in an area where we have really poor unit testing (all drivers). 
> 
> 

It's a straightforward method. Unit tests cover all scenarios that would be there.

I don't think deeper testing is needed for this particular change.

**Comment by BDisp** [comment]
> Before I accept this, I'd like confirmation that this change has been thoroughly tested on Windows, Linux, and the Mac.
> 
> I don't fully understand the code paths/scenarios involved where this method is used and am nervous about introducing a regression in an area where we have really poor unit testing (all drivers).

I confirm that the method is common for all drivers and this is a short way to get the hexadecimal from the rune which is well written. Thanks @pavkam.

**Review by tig — APPROVED** [review]

**Pull request merged**
