### PR TITLE
Fixes #3132 #3138 ComboBox (v2) One key delay when keying down arrow. Up arrow does not move back to searchbox

### LINKED ISSUE #3132: ComboBox (v2) One key delay when keying down arrow to move into dropdown list
When keying down from the search box, you have to key twice to get into the dropdown list. 
It should immediately move into the list. 

This issue is in v2_develop

### PR DESCRIPTION
**Pull request by fergusonr**
Fixes #3132 #3138 - ComboBox one key delay when keying down arrow. Up arrow does not move back to searchbox

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by fergusonr** [comment]
"dotnet test" working locally for me, but two tests are failing on github? Completely unrelated to my changes
```
 Failed Terminal.Gui.InputTests.ResponderTests.Disposing_Event_Notify_All_Subscribers_On_The_First_Container [1 ms]
 Failed Terminal.Gui.InputTests.ResponderTests.Responder_Not_Notifying_Dispose [< 1 ms]
```

**Review by tig — APPROVED** [review]
Awesome. Thank you.

**Comment by BDisp** [comment]
> "dotnet test" working locally for me, but two tests are failing on github? Completely unrelated to my changes
> 
> ```
>  Failed Terminal.Gui.InputTests.ResponderTests.Disposing_Event_Notify_All_Subscribers_On_The_First_Container [1 ms]
>  Failed Terminal.Gui.InputTests.ResponderTests.Responder_Not_Notifying_Dispose [< 1 ms]
> ```

Thanks @fergusonr. I already submitted the PR #3142 that fix this.

**Review by tig — APPROVED** [review]
LGTM!

**Pull request merged**
